### ISSUE TITLE
RSACryptoServiceProvider::VerifyData throws ArgumentNullException when only a public key is used

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#1888]
```
private static void VerifySignature(
    byte[] signature,
    byte[] data,
    string hashAlgorithmName,
    RSAParameters rsaParameters)
{
    RSAParameters publicOnly = new RSAParameters
    {
        Modulus = rsaParameters.Modulus,
        Exponent = rsaParameters.Exponent,
    };

    bool signatureMatched;

    using (var rsa = new RSACryptoServiceProvider())
    {
        rsa.ImportParameters(publicOnly);
        signatureMatched = rsa.VerifyData(data, hashAlgorithmName, signature);
    }

    Assert.True(signatureMatched);
}
```

 Caught Unexpected exception:System.ArgumentNullException: Value cannot be null.
 Parameter name: SafeHandle cannot be null.
    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
    at Internal.NativeCrypto.CapiHelper.Interop.CryptCreateHash(SafeProvHandlehProv, Int32 algId, SafeKeyHandle hKey, CryptCreateHashFlags dwFlags, SafeHa shHandle& phHash)
    at Internal.NativeCrypto.CapiHelper.CreateHashHandle(SafeProvHandle hProv, Byte[] hash, Int32 calgHash)
    at Internal.NativeCrypto.CapiHelper.VerifySign(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 calgKey, Int32 calgHash, Byte[] hash, Byte[] signature)
    at System.Security.Cryptography.RSACryptoServiceProvider.VerifyHash(Byte[] rgbHash, Int32 calgHash, Byte[] rgbSignature)
    at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)

Verified that it works on 4.5.1

**Comment by bartonjs** [comment]
Also applies to RSACryptoServiceProvider::VerifyHash

**Comment by PinpointTownes** [comment]
FYI, a similar ticket has been opened on **aspnet/Security** to track this nasty bug: https://github.com/aspnet/Security/issues/223

**Comment by noeljiangcc** [comment]
I can still reproduce this issue with dnx-coreclr-win-x86.1.0.0-beta6 and "System.Security.Cryptography.RSA": "4.0.0-beta-23109".
Which build includes this fix?
Thanks.

**Comment by bartonjs** [comment]
https://github.com/aspnet/Security/issues/223#issuecomment-118568204 pointed out that the package is fixed, but that you need to update the DNX runtime, because it uses an embedded version of this library.

`dnx-coreclr-win-x86.1.0.0-beta6-12170` is what was observed to be working on the other thread.

**Comment by noeljiangcc** [comment]
Thx, bartonjs. It cannot be reproduce in beta6-12170.

**Comment by noeljiangcc** [comment]
Today, I installed Microsoft ASP.NET and Web Tools 2015 (Beta6) – Visual Studio 2015.(
http://www.microsoft.com/en-us/download/details.aspx?id=48222)
I checked the version of .dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta6\bin\dnx.exe is 1.0.0-beta6-12256. 
The version of .dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta6\bin\System.Security.Cryptography.RSA.dll is 4.6.23109.0.

But this issue still exists.

I am confusing why the newest dnx still has this issue.
So I have to use 12170 dnx?
Will this fix be included in beta7?

Thanks.

**Comment by bartonjs** [comment]
@PinpointTownes, I don't suppose you have any insight as to the dnx packaging/version question that @noeljiangcc asked?  (Short form: dnx-coreclr-win-x86.1.0.0-beta6-12170 let RSA public keys work correctly, but dnx-coreclr-win-x86.1.0.0-beta6-12256 executes as if this bug wasn't fixed).

**Comment by PinpointTownes** [comment]
@bartonjs sadly, no. But @noeljiangcc is right, there was a regression at some point. Even the beta6 release version embeds the buggy RSA package:

```csharp
// System.Security.Cryptography.RSACryptoServiceProvider
public void ImportCspBlob(byte[] keyBlob)
{
	if (this._safeKeyHandle != null && !this._safeKeyHandle.IsClosed)
	{
		this._safeKeyHandle.Dispose();
		this._safeKeyHandle = null;
	}
	this._safeKeyHandle = SafeKeyHandle.InvalidHandle;
	if (RSACryptoServiceProvider.IsPublic(keyBlob))
	{
		SafeProvHandle invalidHandle = SafeProvHandle.InvalidHandle;
		this.AcquireSafeProviderHandle(ref invalidHandle);
		CapiHelper.ImportKeyBlob(invalidHandle, CspProviderFlags.NoFlags, keyBlob, ref this._safeKeyHandle);
		return;
	}
	if (this._safeProvHandle == null)
	{
		this._safeProvHandle = CapiHelper.CreateProvHandle(this._parameters, this._randomKeyContainer);
	}
	CapiHelper.ImportKeyBlob(this._safeProvHandle, this._parameters.Flags, keyBlob, ref this._safeKeyHandle);
}
```

```csharp
[assembly: AssemblyVersion("4.0.0.0")]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: AssemblyDefaultAlias("System.Security.Cryptography.RSA")]
[assembly: AssemblyDescription("System.Security.Cryptography.RSA")]
[assembly: AssemblyFileVersion("4.6.23109.00")]
[assembly: AssemblyInformationalVersion("4.6.23109.00 built by: PROJECTKREL")]
[assembly: AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: AssemblyMetadata("Serviceable", "True")]
[assembly: AssemblyProduct("Microsoft® .NET Framework")]
[assembly: AssemblyTitle("System.Security.Cryptography.RSA")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
```

Surprisingly, both beta6-12170 and the latest beta7 have the correct RSA DLL:

```csharp
// System.Security.Cryptography.RSACryptoServiceProvider
public void ImportCspBlob(byte[] keyBlob)
{
	if (this._safeKeyHandle != null && !this._safeKeyHandle.IsClosed)
	{
		this._safeKeyHandle.Dispose();
		this._safeKeyHandle = null;
	}
	this._safeKeyHandle = SafeKeyHandle.InvalidHandle;
	if (RSACryptoServiceProvider.IsPublic(keyBlob))
	{
		SafeProvHandle invalidHandle = SafeProvHandle.InvalidHandle;
		this.AcquireSafeProviderHandle(ref invalidHandle);
		CapiHelper.ImportKeyBlob(invalidHandle, CspProviderFlags.NoFlags, keyBlob, ref this._safeKeyHandle);
		this._safeProvHandle = invalidHandle; // this line fixes the NRE bug.
		return;
	}
	if (this._safeProvHandle == null)
	{
		this._safeProvHandle = CapiHelper.CreateProvHandle(this._parameters, this._randomKeyContainer);
	}
	CapiHelper.ImportKeyBlob(this._safeProvHandle, this._parameters.Flags, keyBlob, ref this._safeKeyHandle);
}
```

```csharp
[assembly: AssemblyVersion("4.0.0.0")]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: AssemblyDefaultAlias("System.Security.Cryptography.RSA")]
[assembly: AssemblyDescription("System.Security.Cryptography.RSA")]
[assembly: AssemblyFileVersion("4.6.23109.00")]
[assembly: AssemblyInformationalVersion("4.6.23109.00 built by: DDBLD621B-DLAB")]
[assembly: AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: AssemblyMetadata("Serviceable", "True")]
[assembly: AssemblyProduct("Microsoft® .NET Framework")]
[assembly: AssemblyTitle("System.Security.Cryptography.RSA")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
```

The only difference I see is that these DLL have been built by different tools: `PROJECTKREL` vs `DDBLD621B-DLAB`. Could `PROJECTKREL` use older (and buggy) bits?

**Comment by prabhakar-mishra** [comment]
Is there any update on this issue? Beta6 build installed by the Web Tools 2015 (Beta6) has this issue and we can not use this because of the above mentioned issue. Is there later build which fixes this issue and can be used?

**Comment by bartonjs** [comment]
@weshaggard: You know more about the builds/package-flows/downstream-bundling than anone else I know; I don't suppose you have any advice to give?

**Comment by weshaggard** [comment]
Unfortunately I don't know of any magic steps to fix this. @bartonjs we should be able to get another higher version of your packages on our myget feed and presumably someone could explicitly reference that. Although that would assume that DNX isn't pinning the version of this package.
