### ISSUE TITLE
BasicEventSourceTests.TestEventCounter.Test_Write_Metric_EventListener fails on UWP.

### ISSUE THREAD

**Issue by brianrob** [dotnet/corefx#22791]
Test failure on UWP: BasicEventSourceTests.TestEventCounter.Test_Write_Metric_EventListener

This failure appears to be caused by #22422.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170726.01/workItem/System.Diagnostics.Tracing.Tests/analysis/xunit/BasicEventSourceTests.TestEventCounter~2FTest_Write_Metric_EventListener

**Comment by brianrob** [comment]
@vancem, can you please take a look at this?  It appears to be related to #22422, which fixes races in EventCounter.

**Comment by mellinoe** [comment]
I encountered this test failure on my desktop run. Not sure if I should file it here or over in https://github.com/dotnet/corefx/issues/19455, but the test which failed is `Test_Write_Metric_EventListener`.

https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/1912/consoleText

```
      BasicEventSourceTests.TestEventCounter.Test_Write_Metric_EventListener [FAIL]
        System.Diagnostics.Tracing.EventSourceException : An error occurred when writing to a listener.
        ---- Assert.True() Failure
  Finished running tests.  End time=16:15:05.08, Exit code = 0
        Expected: True
        Actual:   False
        Stack Trace:
             at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
             at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* childActivityID, Int32 eventDataCount, EventData* data)
             at System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
             at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, String arg1, Int32 arg2)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs(108,0): at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs(248,0): at BasicEventSourceTests.TestEventCounter.Test_Write_Metric(Listener listener)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs(50,0): at BasicEventSourceTests.TestEventCounter.Test_Write_Metric_EventListener()
          ----- Inner Stack Trace -----
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs(163,0): at BasicEventSourceTests.TestEventCounter.<>c.<Test_Write_Metric>b__2_7(List`1 evts)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs(53,0): at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass0_0.<RunTests>b__0(Event data)
             at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)

```

**Comment by brianrob** [comment]
@mellinoe, you've got the right place.  #19455 is a different failure.

**Comment by vancem** [comment]
I have merge #23025 to add more diagnostics (I could not repro it myself).  

@mellinoe was this deterministic or not?

**Comment by mellinoe** [comment]
@vancem It wasn't deterministic. That one CI job was the only time I've seen it.

**Comment by vancem** [comment]
So I assume that this test has not been disabled correct?   If so we can simply wait for it to happen again with the improved diagnostics.

**Comment by vancem** [comment]
I am going to close the issue as there is nothing to do at this point in time but wait for it to fail again.

Note that my current theory is that because of other activity on the machine, the Timer events do not go off in a timely fashion and the test that is expecting that that Timer event has gone off (it waits 2X the time).   

The additional diagnostics should help confirm this.   However the key here is that it is a TEST problem not a product problem, so it is not as critical.

**Comment by stephentoub** [comment]
> nothing to do at this point in time but wait for it to fail again

It failed again :wink:
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/c6e62e6bfcf631db0b470d20f34fdfd7f7a976d1/workItem/System.Diagnostics.Tracing.Tests/analysis/xunit/BasicEventSourceTests.TestEventCounter~2FTest_Write_Metric_EventListener
```
Unhandled Exception of Type System.Diagnostics.Tracing.EventSourceException
Message :
System.Diagnostics.Tracing.EventSourceException : An error occurred when writing to a listener.\n---- FAILURE: 26 <= 22\nExpected: True\nActual:   False
Stack Trace :
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
   at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* childActivityID, Int32 eventDataCount, EventData* data)
   at System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
   at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, String arg1, Int32 arg2)
   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 102
   at BasicEventSourceTests.TestEventCounter.Test_Write_Metric(Listener listener) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestEventCounter.cs:line 254
   at BasicEventSourceTests.TestEventCounter.Test_Write_Metric_EventListener() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestEventCounter.cs:line 50
----- Inner Stack Trace -----
   at BasicEventSourceTests.TestEventCounter.<>c.<Test_Write_Metric>b__2_7(List`1 evts) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestEventCounter.cs:line 226
   at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass0_0.<RunTests>b__0(Event data) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 54
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
```

**Comment by Jiayili1** [comment]
failed again in CI, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/195/testReport/BasicEventSourceTests/TestEventCounter/Test_Write_Metric_EventListener/

**Comment by ericstj** [comment]
Failed again in https://github.com/dotnet/corefx/pull/23611: https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/2698/consoleFull

**Comment by ericstj** [comment]
And again in https://github.com/dotnet/corefx/pull/23611: https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/2708/consoleFull

**Comment by vancem** [comment]
This is actually not the same issue as @Jiayili1  reported (the test runs several sub-tests and this is failing on a different one.   

#PR 23553 will not address this issue, but it does have changes to the logging, which may give us a bit more information.   I am assuming this is non deterministic and rare.  It may be a pain to track down.

**Comment by ericstj** [comment]
Hit again:
```
      BasicEventSourceTests.TestEventCounter.Test_Write_Metric_EventListener [FAIL]
        System.Diagnostics.Tracing.EventSourceException : An error occurred when writing to a listener.
        ---- Assert.Equal() Failure
        Expected: 4
        Actual:   0
        Stack Trace:
             at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
             at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* childActivityID, Int32 eventDataCount, EventData* data)
             at System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
             at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, String arg1, Int32 arg2)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs(102,0): at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs(255,0): at BasicEventSourceTests.TestEventCounter.Test_Write_Metric(Listener listener)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs(50,0): at BasicEventSourceTests.TestEventCounter.Test_Write_Metric_EventListener()
          ----- Inner Stack Trace -----
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs(88,0): at BasicEventSourceTests.TestEventCounter.<>c.<Test_Write_Metric>b__2_1(List`1 evts)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs(53,0): at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass0_0.<RunTests>b__0(Event data)
  xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
             at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
    Finished:    System.Diagnostics.Tracing.Tests
```

@vancem did you happen to make some fix to the desktop implementation to address this?  Since Diagnostics.Tracing is part of netstandard we're no longer building it in master with #23611 so its possible that the test failure is real and we need to disable this test for desktop.

**Comment by vancem** [comment]
@ericstj - I dont' know of desktop fixes that would explain the failure above (Brian may know of something but I doubt it).  

I have merged #23553, which may help diagnose the problem (although perhaps only marginally).   Please do report further failures (It clearly has not effected some CI jobs (for example the ones I ran for #23553) so some idea of the frequency of failure would be useful to know).

**Comment by ericstj** [comment]
To get an understanding of what fixes were made to that *will not* be in the desktop tracing dll, you can compare master and release/2.0.0:

https://github.com/dotnet/corefx/commits/release/2.0.0/src/System.Diagnostics.Tracing/src
https://github.com/dotnet/corefx/commits/master/src/System.Diagnostics.Tracing/src

I see lots of changes that touch EventCounter.

So your desktop tests are effectively running against this version of the source, even in master after my change #23611: https://github.com/dotnet/corefx/blob/6a645de462c8c42cc7cdd703923c9608e43a1738/src/System.Diagnostics.Tracing/src/System/Diagnostics/Tracing/EventCounter.cs

I suspect that's the root cause of these failures.

**Comment by ericstj** [comment]
Here's the latest, with your additional logging.  https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/2745/consoleText

```
        FAILURE IN SUBTEST: "EventCounter: Log 1 event, explicit poll at end"
        ************* EXCEPTION INFO ***************
        Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: 4
        Actual:   0
           at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:line 35
           at BasicEventSourceTests.TestEventCounter.<>c.<Test_Write_Metric>b__2_1(List`1 evts) in D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs:line 84
           at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass2_0.<RunTests>b__0(Event data) in D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs:line 72
           at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
        *********** END EXCEPTION INFO *************
        ************* LOGGING MESSAGES ***************
        38:55.738 : STARTING Sub-Test EventCounter: Log 1 event, explicit poll at end
        38:55.738 : Sending command MyEventSource to EventSource Enable Options <Options Keywords='ffffffffffffffff' Level'Verbose' ArgsCount='1'
        38:55.739 : Sending command MyEventSource to EventSource Enable Options <Options Keywords='ffffffffffffffff' Level'Verbose' ArgsCount='1'
        38:55.857 : Exception thrown: Assert.Equal() Failure
        Expected: 4
        Actual:   0
        
        *********** END LOGGING MESSAGES *************
        Version of Runtime 4.0.30319.42000
        Version of OS Microsoft Windows NT 6.2.9200.0
        **********************************************
        
        ---- Assert.Equal() Failure
        Expected: 4
        Actual:   0
        Stack Trace:
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs(163,0): at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs(266,0): at BasicEventSourceTests.TestEventCounter.Test_Write_Metric(Listener listener)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs(50,0): at BasicEventSourceTests.TestEventCounter.Test_Write_Metric_EventListener()
          ----- Inner Stack Trace -----
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs(84,0): at BasicEventSourceTests.TestEventCounter.<>c.<Test_Write_Metric>b__2_1(List`1 evts)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs(72,0): at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass2_0.<RunTests>b__0(Event data)
             at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
```

**Comment by danmosemsft** [comment]
@brianrob this is still failing daily.
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170915.02/workItem/System.Diagnostics.Tracing.Tests/analysis/xunit/BasicEventSourceTests.TestEventCounter~2FTest_Write_Metric_EventListener

**Comment by Jiayili1** [comment]
The test `BasicEventSourceTests.TestEventCounter/Test_Write_Metric_EventListener` has failed.

BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\r
    FAILURE IN SUBTEST: \"EventCounter: Log 1 event, explicit poll at end\"\r
    ************* EXCEPTION INFO ***************\r
    Xunit.Sdk.EqualException: Assert.Equal() Failure\r
    Expected: 4\r
    Actual:   2\r
       at Xunit.Assert.Equal<System.Int32>(Int32 expected, Int32 actual, IEqualityComparer$1<Int32> comparer) in C:\\BuildAgent\\work\\cb37e9acf085d108\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 35\r
       at BasicEventSourceTests.TestEventCounter.<>c.<Test_Write_Metric>b__2_1(List$1<$Event> evts) in E:\\A\\_work\\892\\s\\corefx\\src\\System.Diagnostics.Tracing\\tests\\BasicEventSourceTest\\TestEventCounter.cs:line 85\r
       at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass2_0.<RunTests>b__0($Event data) in E:\\A\\_work\\892\\s\\corefx\\src\\System.Diagnostics.Tracing\\tests\\BasicEventSourceTest\\Harness\\EventTestHarness.cs:line 73\r
       at BasicEventSourceTests.EventListenerListener.HelperEventListener.OnEventWritten(EventWrittenEventArgs eventData) in E:\\A\\_work\\892\\s\\corefx\\src\\System.Diagnostics.Tracing\\tests\\BasicEventSourceTest\\Harness\\Listeners.cs:line 400\r
       at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs) in f:\\dd\
    dp\\fxcore\\CoreRT\\src\\System.Private.CoreLib\\shared\\System\\Diagnostics\\Tracing\\EventSource.cs:line 2274\r
    \r
    *********** END EXCEPTION INFO *************\r
    ************* LOGGING MESSAGES ***************\r
    38:33.023 : STARTING Sub-Test EventCounter: Log 1 event, explicit poll at end\r
    38:33.023 : Sending command MyEventSource to EventSource Enable Options <Options Keywords='ffffffffffffffff' Level'Verbose' ArgsCount='1'\r
    38:33.023 : Received Event MyEventSource/EventSourceMessage(ERROR: Exception in Command Processing for EventSource MyEventSource: The API supports only anonymous types or types decorated with the EventDataAttribute. Non-compliant type: $BlockedFromReflection_0_2b600555 dataType.)\r
    38:33.023 : Sending command MyEventSource to EventSource Enable Options <Options Keywords='ffffffffffffffff' Level'Verbose' ArgsCount='1'\r
    38:33.023 : Received Event MyEventSource/EventSourceMessage(ERROR: Exception in Command Processing for EventSource MyEventSource: The API supports only anonymous types or types decorated with the EventDataAttribute. Non-compliant type: $BlockedFromReflection_0_2b600555 dataType.)\r
    38:33.023 : Exception thrown: Assert.Equal() Failure\r
    Expected: 4\r
    Actual:   2\r
    \r
    *********** END LOGGING MESSAGES *************\r
    Version of Runtime 4.0.30319.42000\r
    Version of OS Microsoft Windows NT 6.2.9200.0\r
    **********************************************\r
    \r
    ---- Assert.Equal() Failure\r
    Expected: 4\r
    Actual:   2

        Stack Trace:

           at BasicEventSourceTests.EventTestHarness.RunTests$catch$2() in E:\A\_work\892\s\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs:line 163
       at BasicEventSourceTests.TestEventCounter.Test_Write_Metric($Listener listener) in E:\A\_work\892\s\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs:line 267
       at BasicEventSourceTests.TestEventCounter.Test_Write_Metric_EventListener() in E:\A\_work\892\s\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs:line 51
       at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
       at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
       at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean wrapInTargetInvocationException, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in CallDynamicInvokeMethod:line 16707566
    
    ----- Inner Stack Trace -----
       at BasicEventSourceTests.TestEventCounter.<>c.<Test_Write_Metric>b__2_1(List$1<$Event> evts) in E:\A\_work\892\s\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs:line 85
       at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass2_0.<RunTests>b__0($Event data) in E:\A\_work\892\s\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs:line 73
       at BasicEventSourceTests.EventListenerListener.HelperEventListener.OnEventWritten(EventWrittenEventArgs eventData) in E:\A\_work\892\s\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\Listeners.cs:line 400
       at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Diagnostics\Tracing\EventSource.cs:line 2274
    
Build : Master - 20170918.01 (UWP ILC Tests)
Failing configurations:
- Windows.10.Amd64.ClientRS3-x64
  - Release
- Windows.10.Amd64.ClientRS3-x86
  - Debug

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170918.01/workItem/System.Diagnostics.Tracing.Tests/analysis/xunit/BasicEventSourceTests.TestEventCounter~2FTest_Write_Metric_EventListener

**Comment by vancem** [comment]
To summarize to date:   Earlier in this issue there was some non-determinism in the test that I *THINK* has been addressed.  However we now seem to be running into DETERMINISTIC failure on some particular environments (e.g. Desktop and perhaps .NET Native on Universal Windows Platform (UWP)).

These tests MAY have been passing before because of basically a bug in the infrastructure such that the tests were not actually being run on the environment faithfully (this is Eric's #23611). 

What is also true is that EventCounters are not going to work on sufficiently old version of .NET.  They rely on a new hook called EventSource.EventCommandExecuted that was added relatively recently (I *think* it was 4.6.2, but it might have been 4.6.1, I can't swear).

EventCounter uses reflection to find this hook so that it does not have to distinguish various versions of the .NET Desktop runtime but this means that things build but they will still fail at runtime if the support is not there (it will send a message (to the debugger and to the EventSource), if it fails at runtime, but that may be ignored.  

The upshot of this is that what is likely to be needed is to simply confirm that the failing platforms don't in fact support EventSource.EventCommandExecuted  and if so simply disable the test on that platform.   

Note that in the failure message, it referenced the clr version 4.0.30319.42000.  It is not clear to me whether the environment is 'lieing' or not, but that is a VERY old version of the platform that I would not expect to work.    

It is not clear if we have just one issue (a failure on a UWP test run).   If that is the only failure it seems like UWP being .NET Native, could be fixed to include the necessary API, but it is not clear that this test run is mean to run the latest UWP release or whether it is designed as a compatibility run (in which case we want to keep it running whatever version it is running).

If it is the later, we simply need to disable the test (as it never worked on that platform).   

@brianrob  - can you work with @Jiayili1 and @danmosemsft to figure out if we should be disabling this test and exactly how best to do it?

@Jiayili1 and @danmosemsft  - What is critical here is to understand the point of the tests (is it testing compat or the latest runtime for that platform?).  Can you comment on how this test came to run on UWP (presumably we are taking all CoreFX tests and running time?).   What do we do currently for tests that are known to fail on particular platforms?

**Comment by danmosemsft** [comment]
Thanks @vancem. `Environment.Version` lies as you suspect:
```c#
        public static Version Version
        {
            // Previously this represented the File version of mscorlib.dll.  Many other libraries in the framework and outside took dependencies on the first three parts of this version 
            // remaining constant throughout 4.x.  From 4.0 to 4.5.2 this was fine since the file version only incremented the last part. Starting with 4.6 we switched to a file versioning
            // scheme that matched the product version.  In order to preserve compatibility with existing libraries, this needs to be hard-coded.
            get { return new Version(4, 0, 30319, 42000); }
        }
```

The UWP test run is to make sure that CoreFX and CoreFX tests continue to work against UWP ready for next time we ship UWP. They are on latest CoreRT and latest CoreFX. 

If this test is not expected to work on UWP, we can easily disable it with this attribute on the method or class:
`[SkipOnTargetFramework(TargetFrameworkMonikers.UapAot, "explanation here")]`
or temporarily
`[ActiveIssue("https://github.com/dotnet/corefx/issues/22791", TargetFrameworkMonikers.UapAot)]`

It sounds to me though that it probably should work on UWP and needs a fix somewhere. @brianrob whichever you prefer.

**Comment by danmosemsft** [comment]
This error BTW comes from CoreRT:
https://github.com/dotnet/corert/blob/94744f187ce567c5f1490bfb18491fc54a1c27d7/src/System.Private.CoreLib/shared/System/Diagnostics/Tracing/TraceLogging/Statics.cs#L717

I think the action required is to run this locally and dump what the actual type is. Then either make the test stop passing it on UWP, or mark it as the message instructs: `EventDataAttribute`

**Comment by vancem** [comment]
@brianrob 

It does look like a UWP specific product bug.    For what it is worth the classes that the EventCounter emit seem to be decorated with EventDataAttribute.       

In the past there was an issue with reflection meta-data being stripped unconditionally for things in the framework (I have forgotten the exact details), which would of course cause grief.   Michal Strehovský should have more details on that...

**Comment by brianrob** [comment]
@vancem, I know exactly what you're talking about.  For the interim, I've created #24127 to disable the test on UWP.  We probably need to unblock reflection for EventDataAttribute.  I can investigate this further.

**Comment by stephentoub** [comment]
We no longer run tests on a `uapaot` configuration.
