### ISSUE TITLE
Executing [NetworkInterface.GetAllNetworkInterfaces()] in AWS throws FileNotFoundException

### ISSUE THREAD

**Issue by RufusJWB** [dotnet/corefx#24422]
**Problem**

The method `NetworkInterface.GetAllNetworkInterfaces()` throws always a `FileNotFoundException` if executed in an AWS Lambda environment.

**Analysis**

This function:

    using System.Net.NetworkInformation;
    
    [assembly: Amazon.Lambda.Core.LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]
    
    namespace CheckerLambda
    {
        public class Function
        {
            public string FunctionHandler(Amazon.Lambda.Core.ILambdaContext context)
            {
                // Here we get an "System.IO.FileNotFoundException: Could not find file '/sys/class/net/lo/mtu'."
                var adapters = NetworkInterface.GetAllNetworkInterfaces();

                // do something with 'adapters'
    
                return "This point is never reached";
            }
        }
    }

Leads to this exception if executed in an AWS Lambda environment.

    Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/sys/class/net/lo/mtu'.
    2017-47-04 15:47:21:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
    2017-47-04 15:47:21:    at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
    2017-47-04 15:47:21:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
    2017-47-04 15:47:21:    at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
    2017-47-04 15:47:21:    at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
    2017-47-04 15:47:21:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    2017-47-04 15:47:21:    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
    2017-47-04 15:47:21:    at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
    2017-47-04 15:47:21:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
    2017-47-04 15:47:21:    at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
    2017-47-04 15:47:21:    at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
    2017-47-04 15:47:21:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
    2017-47-04 15:47:21:    at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
    2017-47-04 15:47:21:    at Interop.Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback ipv4Found, IPv6AddressDiscoveredCallback ipv6Found, LinkLayerAddressDiscoveredCallback linkLayerFound)
    2017-47-04 15:47:21:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
    2017-47-04 15:47:21:    at CheckerLambda.Function.FunctionHandler(ILambdaContext context)
    2017-47-04 15:47:21:    at lambda_method(Closure , Stream , Stream , ContextInfo )

Any idea what to do? It could be related to https://github.com/dotnet/corefx/issues/12969

**Comment by stephentoub** [comment]
I believe this should be fixed by https://github.com/dotnet/corefx/pull/13067, which is in .NET Core 2.0.

**Comment by mellinoe** [comment]
Yes, this should be fixed in 2.0. Individual pieces of information may still not be accessible on some systems (MTU in this case), but those exceptions should be catchable / ignorable.

**Comment by RufusJWB** [comment]
That's great to hear. I'll try it, as soon AWS support .net core 2.0!

**Comment by pawepaw** [comment]
I got the same error and i'm pointing .net standard 2.0.

**Comment by sudsy** [comment]
Still getting this error on Lambda even after upgrading to the 2.1 runtime on Lambda.

I am only calling NetworkInterface.GetAllNetworkInterfaces(); not trying to enumerate properties like mtu for instance. There does not appear to be any way to catch the error either.

```
One or more errors occurred. (Could not find a part of the path '/sys/class/net/lo/mtu'.) (Could not find a part of the path '/sys/class/net/vinternal_13/mtu'.) (Could not find a part of the path '/sys/class/net/vtarget_7/mtu'.) (Could not find a part of the path '/sys/class/net/lo/mtu'.) (Could not find a part of the path '/sys/class/net/vinternal_13/mtu'.) (Could not find a part of the path '/sys/class/net/vtarget_7/mtu'.): AggregateException
Could not find a part of the path '/sys/class/net/lo/mtu'.: DirectoryNotFoundException
```

**Comment by galvesribeiro** [comment]
Folks do we have any updates on that? I'm seeing some folks trying to use Orleans clients on Lambdas and they aren't able todo so due to that problem.

**Comment by kcwinner** [comment]
@sudsy I experienced this as well. Tested on my 2.1 lambda with the following (the actual code I am running has a 3rd party library running this):

```
Console.WriteLine("Get Network Adapters");
try
{
    var adapters = NetworkInterface.GetAllNetworkInterfaces();
    Console.WriteLine("Got adapters");
    Console.WriteLine(adapters);
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}
```

Error:
```
System.Net.NetworkInformation.NetworkInformationException (2): An error was encountered while querying information from the operating system. ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path '/sys/class/net/lo/mtu'.) (Could not find a part of the path '/sys/class/net/vinternal_1/mtu'.) (Could not find a part of the path '/sys/class/net/vtarget_1/mtu'.) (Could not find a part of the path '/sys/class/net/lo/mtu'.) (Could not find a part of the path '/sys/class/net/vinternal_1/mtu'.) (Could not find a part of the path '/sys/class/net/vtarget_1/mtu'.) ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/net/lo/mtu'.
```
