### ISSUE TITLE
Test failed: System.Net.NetworkInformation.Tests.UnixPingUtilityTests / PacketSizeIsRespected

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26358]
## Types of failures

```
System.Exception : Ping output was <PING6(64=40+8+16 bytes) ::1 --> ::1
>
---- System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex

at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.<PacketSizeIsRespected>d__1.MoveNext() in /Users/buildagent/agent/_work/79/s/corefx/src/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
at System.String.LastIndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType) in /Users/buildagent/agent/_work/128/s/src/mscorlib/shared/System/String.Searching.cs:line 528
at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.ParseReturnedPacketSize(String pingOutput) in /Users/buildagent/agent/_work/79/s/corefx/src/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs:line 76
at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.<PacketSizeIsRespected>d__1.MoveNext() in /Users/buildagent/agent/_work/79/s/corefx/src/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs:line 47
```

OR 1/7 (4ab83941f6592e6ea9dfee3d87dcdda9e3990eaa):

```
System.Exception : Ping output was <PING6(64=40+8+16 bytes) ::1 --> ::1
24 bytes from ::1, icmp_seq=0 hlim=64>
---- System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
```

OR 12/16 (87216ce10f7b0f5fd51ccdd911896ff3f4e39ccb)

```
System.Exception : Ping output was <>
---- System.ArgumentOutOfRangeException : Length cannot be less than zero.
Parameter name: length
```

## History of failures

Day | Build | OS | Details
--- | --- | --- | ---
11/2 | 20171102.08 | OSX10.12 | 
12/16 | 87216ce10f7b0f5fd51ccdd911896ff3f4e39ccb | OSX10.12 |   
1/7 | 4ab83941f6592e6ea9dfee3d87dcdda9e3990eaa | OSX10.12 |
1/8 | bdd03289d9873cc371e79e7129e528135cdbc2e0 | OSX10.12 |
1/10 | 159249cc136fa994f3262b88a0c289a15a385948 | OSX10.12 |
1/12 | 48a3de14fde5ad5769d0b3fa55b47ca73b7973e3 | OSX10.12 |
1/13 | 1d452515af631807f2edccec256b82c03a060df2 | OSX10.12 |

**Comment by karelz** [comment]
Related to #19435

**Comment by danmosemsft** [comment]
@Priya91 when we looked in #19435 this was a bug in ping.

**Comment by Priya91** [comment]
This has happened only on OSX 10.12, maybe the issue was fixed for OSX 10.13? Can we disable the ping6 tests on OSX 10.12 and keeping only bare minimum for sanity testing?

**Comment by karelz** [comment]
If we have confirmation it is bug in the OS, disabling it on the failing OS makes sense ...

**Comment by wfurt** [comment]
Just a note that ping is very trivial and very old utility. I doubt this is bug in it or bug in OS.
If anything this smells like environmental problem when fail to execute ping properly for some reason.

**Comment by pjanotti** [comment]
We got our first [hit in a PR](https://mc.dot.net/#/user/benaadams/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/b4a14be9ac923f1b929179697a39e11a4374954e) after started to collect stdout and stderr:


```
[/sbin/ping6 -c 1 -s 16 ::1] process exit code is 139.
StdOut:[]
StdErr:[ping6: failed to get receiving hop limit\nping6: \n]
```

That will be
```
11    SIGSEGV      create core image    segmentation violation
```

**Comment by pjanotti** [comment]
This error is already mentioned in #15018, which I didn't see before. The assumption was that in case of seg fault we were going to still have a valid stdout, not the case in the hit above.

**Comment by pjanotti** [comment]
There are errors from CI for PR #26291 but those are caused by changes in that PR itself and affect both macOS 10.12 and 10.13. The timeout is consistently being hit but the output of ping6 is as expected for a good run, it seems like `WaitForExit` is always timing out with that change.

```
System.Exception : [/sbin/ping6 -c 1 -s 16 ::1] process did not exit in 10000 ms.
StdOut:[PING6(64=40+8+16 bytes) ::1 --> ::1
24 bytes from ::1, icmp_seq=0 hlim=64 time=0.070 ms

--- ::1 ping6 statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 0.070/0.070/0.070/0.000 ms
]
StdErr:[]
```

Jenkins [Link](https://mc.dot.net/#/user/tmds/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/d2dc7b58497a97cbcf272032885d1df1fecf6157/workItem/System.Net.Ping.Functional.Tests/analysis/xunit/System.Net.NetworkInformation.Tests.UnixPingUtilityTests~2FPacketSizeIsRespected(payloadSize:%200))

**Comment by pjanotti** [comment]
Another hit in [CI for PR](https://github.com/dotnet/corefx/pull/26354). This time with a different exit code:
```
System.Exception : [/sbin/ping6 -c 1 -s 16 ::1] process exit code is 134.
StdOut:[PING6(64=40+8+16 bytes) ::1 --> ::1
]
StdErr:[ping6: failed to get receiving hop limit
ping6: ping6(57552,0x7fffc87f23c0) malloc: *** error for object 0x7fa7ee5004f8: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
]
```
The exit code indicates:
```
     6     SIGABRT      create core image    abort program (formerly SIGIOT)
```

Jenkins [link](https://mc.dot.net/#/user/KKhurin/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/5e68ae5a0d727b5f049bc4f2c021535b237a7784/workItem/System.Net.Ping.Functional.Tests/analysis/xunit/System.Net.NetworkInformation.Tests.UnixPingUtilityTests~2FPacketSizeIsRespected(payloadSize:%200))

**Comment by pjanotti** [comment]
Two more hits for exit code 134. Hashes:

a7f1bf30fa2dedbcba0b9a37bfb7ad2b36a4f201
243bef769c72c8dc5434da183a1c522d69f040e4
