### ISSUE TITLE
System.Management.Tests fails DateTime_RoundTrip test

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#27652]
System.Management.Tests fails DateTime_RoundTrip test with next log:
```
     System.Management.Tests.ManagementDateTimeConverterTests.DateTime_RoundTrip [FAIL]
        Assert.Equal() Failure
        Expected: 2002-04-08T14:18:35.9780000Z
        Actual:   2002-04-08T15:18:35.9780000Z
        Stack Trace:
           C:\Code\corefx\src\System.Management\tests\System\Management\ManagementDateTimeConverterTests.cs(18,0): at System.Management.Tests.ManagementDateTimeConverterTests.DateTime_RoundTrip()
```
To reproduce this fail - change time zone to `(UTC+7:00) Tomsk` in Windows (temporary).

But I did not find bug in `ManagementDateTimeConverter.ToDateTime` method.

I think that bug located in `TDateTime.ToUniversalTime()` and `TDateTime.ToUniversalTime()` methods.

For `datetime = 2002-04-08T14:18:35.9780000Z`

`TimeZone.CurrentTimeZone.GetUtcOffset(datetime)` return 8 hours offset from UTC because it was Daylight time.

But when I call `datetime.ToLocalTime()` it add only 7 hours (it ignore daylight time).
And when I call `datetime.ToUniversalTime()` it subtract only 7 hours (it ignore daylight time also).

Today Tomsk does not have Daylight time but at  `2002-04-08T14:18:35.9780000Z` Tomsk has Daylight time.

So I think `datetime.ToLocalTime()` and `datetime.ToUniversalTime()` methods have bugs when daylight time different in past and in present.

**Comment by danmosemsft** [comment]
@tarekgh for thoughts

**Comment by tarekgh** [comment]
Yes, this is a limitation in TimeZone class. we encourage people to use TimeZoneInfo class instead. 

please have a look at the remarks section of TimeZone docs:
https://msdn.microsoft.com/en-us/library/system.timezone(v=vs.110).aspx#Remarks

I didn't look at why the test is failed though.

**Comment by tarekgh** [comment]
I looked at the code at 

https://github.com/dotnet/corefx/blob/master/src/System.Management/src/System/Management/ManagementDateTime.cs#L201

and this is definilty wrong and has to be changed to use TimeZoneInfo instead.

I marked this issue as a product bug and not a test bug. 

@danmosemsft who own System.Management can take a look?

**Comment by danmosemsft** [comment]
@pjanotti owns this class. However if it doesn't need a lot of context then @Anipik could do it. @pjanotti ?

**Comment by pjanotti** [comment]
I didn't look at this so if @Anipik can pick it up it will be great. BTW, this should be the same code from full Fx so it should be fixed there too (especially if @tarekgh said so 😸 ). We probably should remove/review all/(if any) other usages of TimeZoneInfo in this namespace.

**Comment by pjanotti** [comment]
@tarekgh should we add a rule to https://github.com/dotnet/platform-compat to use TimeZoneInfo instead of TimeZone?

**Comment by AlexRadch** [comment]
@pjanotti As I read TimeZone can be used to convert times from local time to Coordinated Universal Time (UTC) or vice versa. So it used correctly here.
At `datetime = 2002-04-08T14:18:35.9780000Z` Tomsk time have offset +8 hours! And `ManagementDateTimeConverter.ToDateTime ` use 8 hours.
But datetime.ToUniversalTime() use 7 hours and this is wrong offset.
So I think bug in datetime.ToUniversalTime() but in `ManagementDateTimeConverter.ToDateTime `

**Comment by tarekgh** [comment]
@AlexRadch 

> As I read TimeZone can be used to convert times from local time to Coordinated Universal Time (UTC) or vice versa. So it used correctly here.

I don't think so. you missed the doc part:

```
The TimeZone class supports only a single daylight saving time adjustment rule for the local time zone. As a result, the TimeZone class can accurately report daylight saving time information or convert between UTC and local time only for the period in which the latest adjustment rule is in effect. In contrast, the TimeZoneInfo class supports multiple adjustment rules, which makes it possible to work with historic time zone data.
```
Note that, 2002 can have different daylight adjustment rule than 2018

> So I think bug in datetime.ToUniversalTime() 

Could you clarify why you think so? can you get isolated DateTime repro demonstrate what you think?

**Comment by tarekgh** [comment]
@pjanotti 

> should we add a rule to https://github.com/dotnet/platform-compat to use TimeZoneInfo instead of TimeZone?

That would be a good idea. 
I can expect some areas may care more about the app compatibility than correctness. but in general, no one should use TimeZone class.

**Comment by tarekgh** [comment]
one other note, if you look at 

https://www.timeanddate.com/worldclock/russia/tomsk

you'll see Tomsk doesn't have daylight saving in 2018. so the offset is UTC+7
