### ISSUE TITLE
Leaking System.Net.Http.HttpConnectionPool in WCF web socket tests

### ISSUE THREAD

**Issue by KKhurin** [dotnet/corefx#27884]
It seems that the new web sockets implementation is leaking objects by leaving them rooted by the timers. Here is the typical GC root:
~~~
0:080> !gcroot 0000020209eb6650
HandleTable:
    000001fe883215f8 (pinned handle)
    -> 0000020289ea1038 System.Object[]
    -> 0000020189ea2988 System.Threading.TimerQueue[]
    -> 0000020189ea2a88 System.Threading.TimerQueue
    -> 0000020209eb7b30 System.Threading.TimerQueueTimer
...
    -> 0000020209eb65a0 System.Threading.TimerQueueTimer
    -> 0000020209eb6280 System.Net.Http.HttpConnectionPoolManager
    -> 0000020209eb62c0 System.Collections.Concurrent.ConcurrentDictionary`2[[System.Net.Http.HttpConnectionPoolManager+HttpConnectionKey, System.Net.Http],[System.Net.Http.HttpConnectionPool, System.Net.Http]]
    -> 0000020209eb6548 System.Collections.Concurrent.ConcurrentDictionary`2+Tables[[System.Net.Http.HttpConnectionPoolManager+HttpConnectionKey, System.Net.Http],[System.Net.Http.HttpConnectionPool, System.Net.Http]]
    -> 0000020209eb6438 System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.Net.Http.HttpConnectionPoolManager+HttpConnectionKey, System.Net.Http],[System.Net.Http.HttpConnectionPool, System.Net.Http]][]
    -> 0000020209eb6700 System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.Net.Http.HttpConnectionPoolManager+HttpConnectionKey, System.Net.Http],[System.Net.Http.HttpConnectionPool, System.Net.Http]]
    -> 0000020209eb6650 System.Net.Http.HttpConnectionPool

~~~
The leak is especially fast in stress where we get about 100K leaked pools each 10 minutes of stress run.

**Comment by geoffkizer** [comment]
HttpConnectionPoolManager.Dispose should dispose the timer, so apparently that isn't getting called.  Which would seem to indicate that the SocketsHttpHandler is not getting disposed, either.  @KKhurin does that sound right to you?

We need to fix either way, just trying to narrow down what's happening here.

**Comment by stephentoub** [comment]
We weren't disposing of the handler used by ClientWebSocket.  I put up https://github.com/dotnet/corefx/pull/27900 to address that, and that should fix this specific issue.

However, I'm a little concerned still that there were so many pools still rooted. The timer queue should be using weak references to avoid keeping the timers alive, so if there are still a ton that aren't being finalized, it's possible something else is keeping them alive.  @KKhurin, what does it show for all gcroots for one of these?  It's also possible that the stress run is actually creating many, many more connections than the 100K shown here, and this 100K is just what remains to be cleaned and would if the system was able to process through all of the finalizers and whatnot.

**Comment by pjanotti** [comment]
I confirmed that the big leak is gone, will check if there are remaining issues in cases of failures.

**Comment by pjanotti** [comment]
No leaks showing up in WCF stress using the recycle pool frequency knob.

**Comment by stephentoub** [comment]
Thanks, @pjanotti!

**Comment by sherlock1982** [comment]
I found this in 2.1.4.
Does that mean the issue still exists or it should go away?
We're using WebSockets but I'm not sure it's connected with them.

```
HandleTable:
    00007FA961F415F8 (pinned handle)
    -> 00007FA8D7FFF038 System.Object[]
    -> 00007FA8C8048048 System.Threading.TimerQueue[]
    -> 00007FA8C8048080 System.Threading.TimerQueue
    -> 00007FA8CC45A450 System.Threading.TimerQueueTimer
    -> 00007FA8CBFCE818 System.Threading.TimerQueueTimer
    -> 00007FA8CBFCBCC0 System.Threading.TimerQueueTimer
    -> 00007FA8CBFC7A00 System.Threading.TimerQueueTimer
    -> 00007FA8CBF4ED28 System.Threading.TimerQueueTimer
    -> 00007FA8CBF3A6E0 System.Threading.TimerQueueTimer
    -> 00007FA8CBF299C0 System.Threading.TimerQueueTimer
    -> 00007FA8CBF24DF8 System.Threading.TimerQueueTimer
    -> 00007FA8CBF23A38 System.Threading.TimerQueueTimer
    -> 00007FA8CBF1D410 System.Threading.TimerQueueTimer
    -> 00007FA8CBF1BD78 System.Threading.TimerQueueTimer
    -> 00007FA8CBF168B8 System.Threading.TimerQueueTimer
    -> 00007FA8CBBA5F90 System.Threading.TimerQueueTimer
    -> 00007FA8CBB9DB28 System.Threading.TimerQueueTimer
    -> 00007FA8CBB9C800 System.Threading.TimerQueueTimer
    -> 00007FA8CBD90DC0 System.Threading.TimerQueueTimer
    -> 00007FA8CBD89540 System.Threading.TimerQueueTimer
    -> 00007FA8CBCB80F8 System.Threading.TimerQueueTimer
    -> 00007FA8CBCA3C08 System.Threading.TimerQueueTimer
    -> 00007FA8CBC9D0B0 System.Threading.TimerQueueTimer
    -> 00007FA8CBC9AED0 System.Threading.TimerQueueTimer
    -> 00007FA8CBC9A510 System.Threading.TimerQueueTimer
    -> 00007FA8CBC99390 System.Threading.TimerQueueTimer
    -> 00007FA8CBC968B0 System.Threading.TimerQueueTimer
    -> 00007FA8CBC8FDB0 System.Threading.TimerQueueTimer
    -> 00007FA8CBC8D058 System.Threading.TimerQueueTimer
    -> 00007FA8CBC89228 System.Threading.TimerQueueTimer
    -> 00007FA8CBC86790 System.Threading.TimerQueueTimer
    -> 00007FA8CBC84C60 System.Threading.TimerQueueTimer
    -> 00007FA8CBC849E0 System.Net.Http.HttpConnectionPoolManager
    -> 00007FA8CBC84A28 System.Collections.Concurrent.ConcurrentDictionary`2[[System.Net.Http.HttpConnectionPoolManager+HttpConnectionKey, System.Net.Http],[System.Net.Http.HttpConnectionPool, System.Net.Http]]
    -> 00007FA8CBC84C20 System.Collections.Concurrent.ConcurrentDictionary`2+Tables[[System.Net.Http.HttpConnectionPoolManager+HttpConnectionKey, System.Net.Http],[System.Net.Http.HttpConnectionPool, System.Net.Http]]
    -> 00007FA8CBC84B10 System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.Net.Http.HttpConnectionPoolManager+HttpConnectionKey, System.Net.Http],[System.Net.Http.HttpConnectionPool, System.Net.Http]][]

```

Approx stat:
```
00007fa8e9825ff0     7842       564624 System.Net.Http.HttpConnectionPoolManager
00007fa8e98266e0     7842       815568 System.Net.Http.HttpConnectionPool
00007fa8e97427b8    15564      1992192 System.Net.Http.HttpConnectionSettings
00007fa8e98285f8     7782      2116704 System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.Net.Http.HttpConnectionPoolManager+HttpConnectionKey, System.Net.Http],[System.Net.Http.HttpConnectionPool, System.Net.Http]][]

```

**Comment by sherlock1982** [comment]
I think I know what is the problem. We create a set of HttpClient classes and they're never disposed properly. Is this behavior ok? 
I mean well yes I don't dispose HttpClient but should it go away with GC anyway?
