### ISSUE TITLE
SignedCms considers signature invalid on .NET Core but valid on .NET Framework

### ISSUE THREAD

**Issue by vcsjones** [dotnet/corefx#31073]
While @onovotny and I were experimenting with NuGet package signing on netcoreapp2.1 on Windows, we seem to have run in to a behavioral difference of `SignedCms` between .NET Core and the .NET Framework. The .NET Framework considers a PKCS#7 correctly signed, while .NET Core does not.

When NuGet timestamps a package, [it validates the received timestamp][2] after receiving the timestamp

We noticed that when running on .NET Core 2.1, on Windows, [the validation step][3] fails.

I distilled this down to what appears to be a behavioral difference between .NET Core and Desktop .NET Framework from `SignedCms`.

I produced a [small repro here][1] that basically:

1. Has a base-64 encoded PKCS#7 object in `tst.txt`. This came from `CryptRetrieveTimeStamp` which is the same Win32 API that NuGet is using.
1. Loads it in to a `SignedCms`.
1. Calls `CheckSignature` on the first `SignerInfo`.

```sh
# Does not throw an exception
dotnet run --framework net471
```

and

```sh
# Throw an invalid signature exception
dotnet run --framework netcoreapp2.1
```

Both of these were run on Window 10 x64 1803. 

Further more, it appears that `SignedCms` prevents the PKCS#7 object from round-tripping correctly. The PKCS#7 in `tst.txt` is valid according to the .NET Framework. If I load the signature into a `SignedCms` in .NET Core, then export again, the .NET Framework will not consider the re-exported PKCS#7 CMS valid anymore.

[1]: https://github.com/vcsjones/SignedCmsBug
[2]: https://github.com/NuGet/NuGet.Client/blob/8719f568b6e2d32071fb979cd6877faa8a0d96ee/src/NuGet.Core/NuGet.Packaging/Signing/Timestamp/Rfc3161TimestampRequest.cs#L238
[3]: https://github.com/NuGet/NuGet.Client/blob/e5f07bd816e9b6d82ca20acd71ba450500f93b09/src/NuGet.Core/NuGet.Packaging/Signing/Timestamp/Rfc3161TimestampProvider.cs#L106

**Comment by onovotny** [comment]
I believe this issue requires a patch for .NET Core 2.1 as 2.1 is an LTS release.

**Comment by bartonjs** [comment]
Seems like the problems we fixed in https://github.com/dotnet/corefx/pull/30432/files.

**Comment by vcsjones** [comment]
Thanks. I'll pull down a nightly and give it a shot.

**Comment by vcsjones** [comment]
I appear to be lost in a labyrinth of version numbers and links to nightlies that contain vague references to the number two. However, changing the package reference to 

```xml
<PackageReference Include="System.Security.Cryptography.Pkcs" Version="4.6.0-preview1-26714-03" />
```

My `nuget.config` looks like


```xml
<configuration>
<packageSources>
  <add key="myget.dotnetcore" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
</packageSources>
</configuration>
```

I can still reproduce the issue. Is there a better way of testing / grabbing a 2.1.3 build that contains the fix?

**Comment by bartonjs** [comment]
Partially confirmed, if I disable the sorting required for SET-OF under DER, the SignerInfo digest is `A46F7471F64F2B6DB38A9A540AF64525FB448A047C3B17106D75CDBE2ED18D0E`

**Comment by vcsjones** [comment]
Thanks for taking a look. Very appreciated.

**Comment by bartonjs** [comment]
It seems that Windows has some sort of "try the right way, try using the document order" fallback.  It also seems that DigiCert is not RFC-compliant when signing timestamps (because they're the ones who signed it without sorting the attributes).

**Comment by vcsjones** [comment]
I pinged DigiCert so they are at least aware of the issue.

**Comment by bartonjs** [comment]
Oh, good, that was on my TODO list :)

**Comment by clintwilson** [comment]
Looking into this a bit further (thanks Kevin!).
Is this from our http://timestamp.digicert.com TSA?
I don't have an environment set up to reproduce this immediately, is there an example signed file or asn.1 structure that could be provided?

**Comment by vcsjones** [comment]
@clintwilson take a look at https://github.com/vcsjones/SignedCmsBug in the `tst.txt` file.

**Comment by bartonjs** [comment]
@clintwilson Yeah, I submitted a request to http://timestamp.digicert.com earlier this morning, and in the signed file the SigningCertificate attribute (1.2.840.113549.1.9.16.2.12, 43 bytes) and MessageDigest attribute (1.2.840.113549.1.9.4, 47 bytes) are written down not in sorted order.  The digest over the attribute block (which should be a DER SET-OF, which requires sorting) was done over the SET-OF in its file order (of those two being backwards).

The same problem present in the sample from @vcsjones is present in mine at https://github.com/dotnet/corefx/pull/31127/files#diff-8143c14c7c674b77af11dc0449b2243aR303

**Comment by vcsjones** [comment]
@clintwilson the relevant specification is X.690, section 11.6:

>The encodings of the component values of a set-of value shall appear in ascending order, the encodings being compared as octet strings with the shorter components being padded at their trailing end with 0-octets. NOTE – The padding octets are for comparison purposes only and do not appear in the encodings.

**Comment by bartonjs** [comment]
Shiproom template
Description

If the creator of a CMS SignedData document does not sort a signer's signed attributes before computing their signature then .NET Core will report the signature as invalid, but .NET Framework reports it as valid.

Customer Impact

Customers who receive signed documents which were built over unsorted attributes will be told they are invalid on .NET Core, even if they were told they were valid on .NET Framework.  Since at least one free cryptographic time-stamping service is known to have this behavior, it can lead to situations where .NET Framework says a Signed NuGet Package is valid, but .NET Core says it is invalid.

Regression?

Behavioral regression from .NET Framework, the .NET Core implementation was new for netcoreapp2.1.

Risk

Low.  The solution is just to try processing attributes in the file-specified order if sorted order fails, which matches the Crypt32 behavior.

**Comment by vcsjones** [comment]
@bartonjs 

Hi Jeremy. Thanks for the PR. I just took a look through it and it appears there is a small issue yet to be addressed since I only see changes to how the validation was performed.

Perhaps I should make a new issue to track it separately. The netcoreapp2.1 `SignedCms` does not round-trip the CMS correctly. For example, continuing from my example repo in the initial issue...

```csharp
//Run this as netcoreapp2.1
var contents = File.ReadAllText(@"tst.txt");
var bytes = Convert.FromBase64String(contents);
var cms = new SignedCms();
cms.Decode(bytes);
var reEncoded = cms.Encode();
File.WriteAllText("exported.txt", Convert.ToBase64String(reEncoded));
```

Then with net471

```csharp
//Run this as net471
var contents = File.ReadAllText(@"exported.txt");
var bytes = Convert.FromBase64String(contents);
var cms = new SignedCms();
cms.Decode(bytes);
cms.SignerInfos[0].CheckSignature(verifySignatureOnly: true);
```

I suspect that the netcoreapp2.1 SET OF is being re-exported with the correct DER SET OF ordering and now the digest does not match anymore. Some observations.

1. net471 roundtrips correctly. So it seems to preserve the incorrect order of the SET OF sorting. If I run the first block of code as net471 and the second as net471, it will not raise an invalid signature exception.

2. This still presents a problem with nuget timestamps that were _made_ using netcoreapp2.1, which I don't think is happening yet. The issue seems to be that Nuget is loading the timestamp in to a `SignedCms` object, the [re-encoding it later](https://github.com/NuGet/NuGet.Client/blob/51bfe5f76b546c9c145cad81c33c4ae2c3d3b3d8/src/NuGet.Core/NuGet.Packaging/Signing/Native/NativeCms.cs#L335) as raw bytes, which I believe will end up with an invalid countersignature.

**Comment by onovotny** [comment]
Re #2, I am actively creating timestamps with .NET Core for NuGet. But, it's not re-exporting, rather, I'm packing away the native bytes from Crypt32 and only native functions are manipulating the data after the timestamp.

You can see exactly what I had to do to avoid encoding/reencoding with SignedCms with .NET Core to get it to work here:
https://github.com/onovotny/NuGet.Client/commit/a77bcbcf746fee5bef8582da9889bd41f6d9560d

**Comment by bartonjs** [comment]
```C#
[Fact]
public static void VerifyUnsortedAttributeSignature_ImportExportImport()
{
    SignedCms cms = new SignedCms();
    cms.Decode(SignedDocuments.DigiCertTimeStampToken);

    // Assert.NoThrows
    cms.CheckSignature(true);

    byte[] exported = cms.Encode();
    cms = new SignedCms();
    cms.Decode(exported);

    // Assert.NoThrows
    cms.CheckSignature(true);
}
```

Fails on the last CheckSignature.  I'll also add one for countersigning and additional-signing.

I'm sad at the amount of code required to go from "spec compliant" to "real-world compatible".

**Comment by vivmishra** [comment]
Approved for 2.1.5

**Comment by danmosemsft** [comment]
Moving label to PR per new process

**Comment by karelz** [comment]
Fixed in release/2.1 branch in PR #31325. Will be part of 2.1.5 release.

**Comment by secana** [comment]
I ran into the same issue. I've updated the `System.Security.Cryptography.Pkcs` package to version *4.6.0-preview.18571.3*. This doesn't lead to the expected "valid signature" on .Net Core but instead a `CryptographicException: ASN1 corrupted data.` exception is thrown on `signedCms.Decode(rawCerts)`. 

The same code under the .Net Framework works fine and the signature is verified as valid. Any ideas how to get the signature validation running on .Net Core?

**Comment by vcsjones** [comment]
@secana can you open a new issue, and ideally provide a CMS or steps to reproduce?

**Comment by secana** [comment]
@vcsjones thx for the fast replay. New issue is here https://github.com/dotnet/corefx/issues/34202 with attached CMS and steps to reproduce.

**Comment by vcsjones** [comment]
To close the loop on a thread here, I got word from DigiCert (@clintwilson) that their TSA is now properly sorting DER sequences.

I tried several timestamp I produced a few minutes ago, and validating the timestamp did not use the `compatMode: true` path for `ValidateSignature`.

Thanks Clint!

/cc @bartonjs @onovotny
