### ISSUE TITLE
Regression: 2.1+ doesn't respect SocketOptionName.ReuseAddress on Linux box

### ISSUE THREAD

**Issue by sergey-brutsky** [dotnet/corefx#34628]
Here is a snippet of code
```csharp
using System;
using System.Net;
using System.Net.Sockets;

namespace ConsoleApp1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
            socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);            
            socket.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.AddMembership, new MulticastOption(IPAddress.Parse("224.0.0.50")));
            socket.Bind(new IPEndPoint(IPAddress.Any, 9898));

            Console.WriteLine("Bind socket sucessfully");
            Console.Read();
            socket.Close();
        }
    }
}
```

If we run 2 instances of this program on linux box 
```bash
Linux testhost 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
```

We will see that it produces the issue
```
dotnet ConsoleApp1.dll 

Unhandled Exception: System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at ConsoleApp1.Program.Main(String[] args) in C:\temp\ConsoleApp1\Program.cs:line 14
Aborted
```
But if we run it against dotnet 2.0 everything works fine.
If we run this code against dotnet 2.1 or 2.2 on windows box everything also works fine.

So I suspect that something is broken in dotnet 2.1 & 2.2 runtime in the architecture x86_64
 
Here is dotnet version installed on the target linux box
```
 dotnet --info

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by stephentoub** [comment]
This looks like a dup of https://github.com/dotnet/corefx/issues/32027 which was fixed by https://github.com/dotnet/corefx/pull/32046.  Have you tested on 3.0?

**Comment by sergey-brutsky** [comment]
Hi @stephentoub, you mean try to run the same code on dotnet core 3.0 preview ?
As far as I know dotnet core 3.0 is not released yet

**Comment by stephentoub** [comment]
@sergey-brutsky, yup, I just meant would you be able to try it on the preview, or on a daily build, or some such thing.  I'm pretty sure the issue has already been addressed in master, but confirmation would be great if you're able. Thanks!

**Comment by sergey-brutsky** [comment]
I can confirm that the snippet of code above works perfectly fine on version v3.0.0-preview-27122-01 on linux box `Linux testhost 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux`. So in .net core 3.0 this bug is fixed.

But as I know microsoft claims that .net core 2.1 is LTS release so why this issue is not fixed in LTS ?
@stephentoub ?

**Comment by stephentoub** [comment]
> But as I know microsoft claims that .net core 2.1 is LTS release so why this issue is not fixed in LTS ?

Not every issue is fixed in LTS.  Because it needs to be very-high quality and very stable, there's a very high bar for what changes are ported back to it.

@karelz can speak to what would be needed to make that happen here.

**Comment by sergey-brutsky** [comment]
@karelz I don't know if this is high-impact issue or not.
For me its weird, there is no work around except using runtime 2.0 or unstable preview

**Comment by karelz** [comment]
@sergey-b-berezin understood. Every product in the world has bugs. Unless the bugs are blocking / high-impact, waiting for next release is often the best option.

**Comment by karelz** [comment]
Duplicate of #32027
