### ISSUE TITLE
System.Security.Claims.Claim..ctor parameter checks are too restrictive in CoreCLR

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/corefx#3667]
There is a behaviour difference in `System.Security.Claims.Claim...ctor` that got introduced in CoreCLR but this check does not exist in Desktop. As such, there are scenarios such as creating an anonymous identity (i.e., GenericIdentity with no subject name) that now breaks in CoreCLR. 

Sample Repro: 

    public static void Main()
    {
        System.Security.Principal.GenericIdentity identity = new System.Security.Principal.GenericIdentity(string.Empty); 
    }

The difference is a change in the way the System.Security.Claims.Claim constructor works - the empty string (valid value in desktop) is now treated the same as null (an invalid value), and therefore the call fails with the exception below

```
System.ArgumentNullException : Value cannot be null.
Parameter name: value
Stack Trace:
    at System.Security.Claims.Claim..ctor(String type, String value, String valueType, String issuer, String originalIssuer, ClaimsIdentity subject, String propertyKey, String propertyValue)
    at System.Security.Principal.GenericIdentity.AddNameClaim()
```

This was discovered while testing basic WCF net.tcp scenarios and is considered a major blocker for WCF. dotnet/wcf#387 tracks fixing this issue in the WCF repo

cc: @joshfree

**Comment by joshfree** [comment]
@bartonjs is going to fix the two if-checks that were regressed;

**Comment by iamjasonp** [comment]
Thanks :) Is there an ETA for this, @bartonjs? This one's quite pressing for at least one of our core scenarios.

**Comment by bartonjs** [comment]
Since it sounds like it's blocking I'll float it up in my priority queue.  Unless something catches fire while I'm asleep I'll probably start poking around at this in the morning :smile:.

**Comment by bartonjs** [comment]
@iamjasonp This is now fixed in TFS, so it should be in the packages that build tonight.

**Comment by iamjasonp** [comment]
Thanks @bartonjs! I'll keep an eye on this tonght

**Comment by bartonjs** [comment]
@iamjasonp I'm going to go ahead and close this issue, if you don't see improved binaries show up feel encouraged to reopen it.

**Comment by tushargupta51** [comment]
@bartonjs I am still seeing the issue the 23408 version of System.Security.Claims here: https://www.myget.org/gallery/dotnet-core/. Is that supposed to have the fix?

**Comment by bartonjs** [comment]
@tushargupta51 Hmm, I just pulled down that package and extracted the dotnet flavor of the DLL; the IL looks like it was corrected to me:

```
  IL_0011:  ldarg.1
  IL_0012:  brtrue.s   IL_001f
  IL_0014:  ldstr      "type"
  IL_0019:  newobj     instance void [System.Runtime]System.ArgumentNullException::.ctor(string)
  IL_001e:  throw
  IL_001f:  ldarg.2
  IL_0020:  brtrue.s   IL_002d
  IL_0022:  ldstr      "value"
  IL_0027:  newobj     instance void [System.Runtime]System.ArgumentNullException::.ctor(string)
```

It's just checking for null, not IsNullOrEmpty.

dnx-coreclr-win-x86.1.0.0-beta7 appears to have included System.Security.Claims.dll as part of the runtime package, so if you're using dnx you might need to update that package (though I couldn't really say what the official/supported way of doing that is)

**Comment by tushargupta51** [comment]
@bartonjs I have just this statement in my console app: Claim c = new Claim("test", string.Empty);

Included all these packages:
                "System.Console": "4.0.0-beta-23408",
                "System.Security.Claims": "4.0.1-beta-23408",
                "System.Security.Principal": "4.0.1-beta-23408",
                "System.Runtime": "4.0.21-beta-23408",
                "System.Runtime.Extensions": "4.0.11-beta-23408"
but still error persists. How else can I test it?

@iamjasonp were you able to verify the fix?

**Comment by iamjasonp** [comment]
I tried pulling this package earlier directly from Myget (beta-23408) decompiled, and verified the fix exists. However, I believe that the newest package is being clobbered by other dependencies in the chain

For example, in the WCF case, we depend on System.Security.Principal.Windows/4.0.0-beta-23324 which depends explicitly on S.Security.Claims/4.0.0

My read of the package resolution algo seems to state that given a bunch of conflicting versions, lowest version wins. 

What I ended up doing was: 
* create the test app and build - let the package restore happen,
* download the Myget package, 
* extract it (it's just a zip file with a different extension), 
* clobber the existing dll with the newly-downloaded dll
* run

After that, I was able to verify the fix - in that respect, I think we're good :smile: just that someone may have to go through the corefx repo and bump dependencies up.

**Comment by tushargupta51** [comment]
@iamjasonp We are creating a claim with an empty value in our tests and this issue is making a test fail. We cannot do the manual dll override. @bartonjs Do you know when the dependencies issue will be fixed?

**Comment by bartonjs** [comment]
@tushargupta51 Do you have a sample of what's failing? How are you running it? (dnx, corerun, some other thing I don't know about, etc)

**Comment by tushargupta51** [comment]
@bartonjs I created a console app usign VS2015 and this is what I have in Program.cs

        public void Main(string[] args)
        {
            try
            {
                Claim c = new Claim("test", string.Empty);
                Console.WriteLine("heelo");
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            Console.ReadLine();
        }

Project.json is:

{
    "version": "1.0.0-*",
    "description": "ConsoleApp5 Console Application",
    "authors": [ "tugupta" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "dependencies": {
    },

    "commands": {
        "ConsoleApp5": "ConsoleApp5"
    },

    "frameworks": {
        "dnxcore50": {
            "dependencies": {
                "System.Console": "4.0.0-beta-*",
                "System.Security.Claims": "4.0.1-beta-*"
            }
        }
    }
}

I am using dnx-coreclr-x86 1.0.0-beta8 to test the app.

**Comment by bartonjs** [comment]
> I am using dnx-coreclr-x86 1.0.0-beta8 to test the app.

That's the dependency problem you're running into.  DNX has a copy of the runtime, which functions similar to the GAC in that it always wins over a local DLL.  If you were to take the extracted version of an updated System.Security.Claims.dll and overwrite the one in ~/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-rc1-\<yourversion\>/bin it would probably fix your problem locally.

I don't really have any insight as to how often they pull new packages into their builds, so I really can't say how long before it "just works" out of the box, sorry.

**Comment by iamjasonp** [comment]
If you end up having a project.lock.json file, it might help with discovering what is happening. I did a bit of sleuthing to discover that our package refs were being clobbered.
