### ISSUE TITLE
[Debian 10] Test failure: System.Net.Security.Tests.ApmSslStreamSystemDefaultTest/ClientAndServer_OneOrBothUseDefault_Ok(clientProtocols: Default, serverProtocols: null) 

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#38444]
Test `System.Net.Security.Tests.ApmSslStreamSystemDefaultTest/ClientAndServer_OneOrBothUseDefault_Ok(clientProtocols: Default, serverProtocols: null) ` has failed.

Message :
```
System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
---- Interop+OpenSsl+SslException : SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
-------- Interop+Crypto+OpenSslCryptographicException : error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available
```
Stack Trace :
```
  at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 713
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 557
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 528
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 398
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 312
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 234
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 222
   at System.Net.Security.Tests.ApmSslStreamSystemDefaultTest.<>c__DisplayClass0_0.<AuthenticateClientAsync>b__0(AsyncCallback callback, Object state) in /_/src/System.Net.Security/tests/FunctionalTests/SslStreamSystemDefaultsTest.cs:line 177
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs:line 777
   at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskFactory.cs:line 886
   at System.Net.Security.Tests.ApmSslStreamSystemDefaultTest.AuthenticateClientAsync(String targetHost, X509CertificateCollection clientCertificates, Boolean checkCertificateRevocation, Nullable`1 protocols) in /_/src/System.Net.Security/tests/FunctionalTests/SslStreamSystemDefaultsTest.cs:line 176
   at System.Net.Security.Tests.SslStreamSystemDefaultTest.ClientAndServer_OneOrBothUseDefault_Ok(Nullable`1 clientProtocols, Nullable`1 serverProtocols) in /_/src/System.Net.Security/tests/FunctionalTests/SslStreamSystemDefaultsTest.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount) in /_/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 282
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions) in /_/src/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs:line 120
----- Inner Stack Trace -----
```
Build: -[20190610.76](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190610.76)(Master)

Failing configurations:

- Debian.10.Amd64.Open-x64-Release
Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190610.76/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.ApmSslStreamSystemDefaultTest~2FClientAndServer_OneOrBothUseDefault_Ok(clientProtocols:%20Default,%20serverProtocols:%20null)

**Comment by bartonjs** [comment]
@davidsh Debian 10 is run in the rolling builds for 3.0; these tests either should be fixed, or disabled so they don't interfere with release/3.0 hygiene.  (As release/3.0 gets closer to RTM eventually we'll make all configs also be run on PRs)

**Comment by davidsh** [comment]
>@davidsh Debian 10 is run in the rolling builds for 3.0; these tests either should be fixed, or disabled so they don't interfere with release/3.0 hygiene. (As release/3.0 gets closer to RTM eventually we'll make all configs also be run on PRs)

There seems be other Debian 10 TLS/SSL related failures, see #38919  I think there is some issue with OpenSsl on Debian 10 that needs further investigating.

**Comment by wfurt** [comment]
This and #38919 are failing in tests requiring Tls1.0 and Tls1.1 and it is easy to reproduce. I did some tests with `openssl s_client --tls1_1` and it seems to work as expected. So it may be issue with the portable layer.
The image we use has OpenSsl 1.1.1c.

**Comment by ViktorHofer** [comment]
Tomas have you had time to diagnose this further? We still have a large amount of failing tests because of this in our rolling builds and need to drive them down for 3.0. Thanks

**Comment by davidsh** [comment]
>Tomas have you had time to diagnose this further? We still have a large amount of failing tests because of this in our rolling builds and need to drive them down for 3.0. Thanks

Could it be related to #39384 39372

**Comment by bartonjs** [comment]
> Could it be related to #39372 ?

Shouldn't be.  That would be an assert (in debug builds) or a default `CryptographicException`.  This one is interpreting an error state from OpenSSL: `Interop+Crypto+OpenSslCryptographicException : error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available`

**Comment by wfurt** [comment]
I did more testing with openssl. On my Ubuntu 16, I can start `openssl s_server -cert test.pem -key test.pem` and than connect using  `openssl s_client` with TLS1.0, 1.1 & 1.2. With OpenSSl 1.1.1c from Debian I can connect only with TLS1.2 and 1.3. 

I was suspicious that support for older  protocol versions was removed/disabled but I can still run `openssl s_server -tls1` and connect using TLS1.0 (or 1.1) 

I also tried simple test code:
```c#
using System;
using System.Net;
using System.Net.Sockets;
using System.IO;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Security.Authentication;
using System.Threading.Tasks;
using System.Threading;

namespace aa
{
    class Program
    {
        static void Main(string[] args)
        {
            Server().GetAwaiter().GetResult();
        }

        static async Task Server()
        {
            byte[] AllData = System.IO.File.ReadAllBytes("/mnt/merged.pfx");
            var cert = new X509Certificate2(AllData, "", X509KeyStorageFlags.DefaultKeySet);

            SslServerAuthenticationOptions options = new SslServerAuthenticationOptions()
                     {
                                      ClientCertificateRequired = false,
                                      ServerCertificate = cert,
                                      EnabledSslProtocols = SslProtocols.Tls,
                                      CertificateRevocationCheckMode = X509RevocationMode.NoCheck,
                      };


            TcpListener listener = new TcpListener(IPAddress.Parse("0.0.0.0"), 5555);
            listener.Start();

            TcpClient server = listener.AcceptTcpClient();

            SslStream sserver = new SslStream(server.GetStream(), false, null, null);
            await sserver.AuthenticateAsServerAsync(options, CancellationToken.None);
            Console.WriteLine("SSL Done");
        }
    }
}
```

and I'm failed to connect even if I tried all TLS version. It works as expected with TLS1.2 and 1.3 (e.g. I can connect with that exact protocol version) and same code works with TLS1.0 on older OpenSSL version. 

It seems TLS1.0 and 1.1 does not work by default but it is possible to make it working at least using OpenSSL tools. 
So I view this as product bug. 


Some of the tests are failing just because they happened to use old TLS. For example failing SNI tests can be fixed by modifying SslServerAuthenticationOptions as 
``` c#
EnabledSslProtocols = PlatformDetection.SupportsTls13 ? SslProtocols.Tls13 : SslProtocols.Tls,
```
(or using SslProtocols.Tls12 if available on all supported OSes)

**Comment by wfurt** [comment]
here is example of TLS1.0
```
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : ECDHE-RSA-AES256-SHA
```
The client hello has only 9 ciphers in the list.
`openssl ciphers DEFAULT` is bit shorter too comparing to Ubuntu.
```
helixbot@36a3cbfe8fdc:/mnt/wfurt-corefx-deb10/src/System.Net.Security/src$ openssl ciphers DEFAULT
TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:RSA-PSK-AES256-GCM-SHA384:DHE-PSK-AES256-GCM-SHA384:RSA-PSK-CHACHA20-POLY1305:DHE-PSK-CHACHA20-POLY1305:ECDHE-PSK-CHACHA20-POLY1305:AES256-GCM-SHA384:PSK-AES256-GCM-SHA384:PSK-CHACHA20-POLY1305:RSA-PSK-AES128-GCM-SHA256:DHE-PSK-AES128-GCM-SHA256:AES128-GCM-SHA256:PSK-AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:ECDHE-PSK-AES256-CBC-SHA384:ECDHE-PSK-AES256-CBC-SHA:SRP-RSA-AES-256-CBC-SHA:SRP-AES-256-CBC-SHA:RSA-PSK-AES256-CBC-SHA384:DHE-PSK-AES256-CBC-SHA384:RSA-PSK-AES256-CBC-SHA:DHE-PSK-AES256-CBC-SHA:AES256-SHA:PSK-AES256-CBC-SHA384:PSK-AES256-CBC-SHA:ECDHE-PSK-AES128-CBC-SHA256:ECDHE-PSK-AES128-CBC-SHA:SRP-RSA-AES-128-CBC-SHA:SRP-AES-128-CBC-SHA:RSA-PSK-AES128-CBC-SHA256:DHE-PSK-AES128-CBC-SHA256:RSA-PSK-AES128-CBC-SHA:DHE-PSK-AES128-CBC-SHA:AES128-SHA:PSK-AES128-CBC-SHA256:PSK-AES128-CBC-SHA
```

**Comment by karelz** [comment]
@krwq do you have time to help with this one please?

**Comment by krwq** [comment]
I'm not particularly concerned about these test failures where one side is allowed to speak <= Tls1.1 and the other is allowed to speak Tls1.3 (default). Opting into TLS 1.3 adds a lot of restrictions on what ciphersuites can be used and only TLS1.3 and some TLS1.2 cipher suites match those critieria.

For tests which use default/TLS1.3 and other side TLS1.0/1.1 we should instead of passing default pass all protocols except TLS 1.3 similarly as we do here: https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/tests/FunctionalTests/SslStreamNegotiatedCipherSuiteTest.cs#L29

**Comment by davidsh** [comment]
So, you consider this a test bug and not a real product related scenario that customers would do?

If so, can we fix the test to be better and more realistic of the scenarios we should be testing?

**Comment by krwq** [comment]
@davidsh correct, this does not look like product bug but rather improper usage (or rather - update your client/server scenario).

TLS 1.3 made a breaking change of making stuff more secure and trusting less stuff which means that client/server using TLS 1.3 by default will not trust anything which doesn't speak at least TLS 1.2.

Having said that, it is a realistic scenario that you might want to talk to the old server so I believe we should just modify test to opt-out of TLS 1.3 (so as mentioned above, instead of using default we should use ALL minus TLS1.3 when trying to talk to old clients)

**Comment by davidsh** [comment]
@krwq Can you make a PR to fix this?  And after than prep one for release/3.0?

**Comment by krwq** [comment]
@davidsh I can make one but I'll need a Dockerfile, docker image or some vm for testing on that specific configuration

**Comment by davidsh** [comment]
>but I'll need a Dockerfile, docker image or some vm for testing on that specific configuration

@wfurt or @wtgodbe can help point to the right Docker image.

**Comment by krwq** [comment]
I'm actually considering to make this scenario always fail when TLS 1.3 is available (basically restrict OpenSSL further meaning that if your openssl can support TLS 1.3 then SslProtocols.None would imply TLS 1.2 or TLS 1.3 rather than different result depending on OpenSSL's build (i.e. with my latest OpenSSL 1.1.1c this test is passing where I don't think it should). cc: @bartonjs 

I'm a bit torn on this though since on one hand I'd prefer to use OS defaults but on the other I'd prefer we always did what OpenSsl build on Debian did.

**Comment by wfurt** [comment]
we should also make sure Tls1.0 and Tls1.1 works when explicitly configured.

**Comment by bartonjs** [comment]
The unspecfied protocols should be the OS/library defaults.  They can be changed in config.  We shouldn't interfere.

**Comment by krwq** [comment]
fair enough, will update the tests

**Comment by krwq** [comment]
hmm, seems there is some product bug here on top of test issues. This mostly matches with what @wfurt wrote above, I'll investigate further.

I've already tried clearing security options, added all known legacy flags to ssl options but it still won't connect when forcing TLS 1.0 when s_client does.

**Comment by krwq** [comment]
Ok I think I know what's wrong. We currently set protocols using SSL_CTX_set_options explicitly but there is also orthogonal way to set that (orthogonal: they end up combining restrictions).

We need to clear that when doing explicit set:

```csharp
    SSL_CTX_set_min_proto_version(ctx, 0);
    SSL_CTX_set_max_proto_version(ctx, 0);
```

I will send a PR after I finish investigating remaining test (there were more than 50 failing tests when I started)

**Comment by karelz** [comment]
Wow, impressive turnaround time, thank you @krwq!

**Comment by karelz** [comment]
Fixed in master (5.0) in PR #39579 and also in release/3.0 branch (3.0) in PR #39820.
