### ISSUE TITLE
System.Text.Json Deserialization - Can't parse DateTime.MinValue if UTC offset is greater than 0

### ISSUE THREAD

**Issue by mholo65** [dotnet/corefx#39067]
Found this issue while trying to build and run tests for `System.Text.Json`

Example stacktrace from `System.Text.Json.Serialization.Tests.ObjectTests.ReadSimpleTestClassWithSimpleTestStruct`

```
System.Text.Json.JsonException : The JSON value could not be converted to System.DateTime. Path: $.MySimpleTestStruct.MyDateTime | LineNumber: 0 | BytePositionInLine: 912.\r\n---- System.FormatException : The JSON value is not in a supported DateTime format.
at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex) in C:\Users\mb\src\gh\corefx\src\System.Text.Json\src\System\Text\Json\ThrowHelper.Serialization.cs:line 172
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack) in C:\Users\mb\src\gh\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.cs:line 124
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader) in C:\Users\mb\src\gh\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.Helpers.cs:line 22
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options) in C:\Users\mb\src\gh\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs:line 74
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options) in C:\Users\mb\src\gh\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs:line 31
   at System.Text.Json.Serialization.Tests.ObjectTests.ReadSimpleTestClassWithSimpleTestStruct() in C:\Users\mb\src\gh\corefx\src\System.Text.Json\tests\Serialization\Object.ReadTests.cs:line 319
----- Inner Stack Trace -----
   at System.Text.Json.Utf8JsonReader.GetDateTime() in C:\Users\mb\src\gh\corefx\src\System.Text.Json\src\System\Text\Json\Reader\Utf8JsonReader.TryGet.cs:line 392
   at System.Text.Json.Serialization.Converters.JsonConverterDateTime.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in C:\Users\mb\src\gh\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\Converters\JsonValueConverterDateTime.cs:line 11
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader) in C:\Users\mb\src\gh\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonPropertyInfoNotNullable.cs:line 25
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader) in C:\Users\mb\src\gh\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonPropertyInfo.cs:line 324
   at System.Text.Json.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state) in C:\Users\mb\src\gh\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.HandleValue.cs:line 28
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack) in C:\Users\mb\src\gh\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.cs:line 50
```

Steps to reproduce:
1. Set TimeZone to something that has an UTC offset larger than 0
2. Run following code:
```csharp
class Class
{
    public DateTime MyDateTime {get; set;}
}
class Program
{
    static void Main(string[] args)
    {
        var json = "{\"MyDateTime\": \"0001-01-01T00:00:00\"}";
        var c = System.Text.Json.JsonSerializer.Deserialize<Class>(json);

        Console.WriteLine(c.MyDateTime);
    }
}
```
3. This should give same exception
```
Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.DateTime. Path: $.MyDateTime | LineNumber: 0 | BytePositionInLine: 36.
 ---> System.FormatException: The JSON value is not in a supported DateTime format.
   at System.Text.Json.Utf8JsonReader.GetDateTime()
   at System.Text.Json.Serialization.Converters.JsonConverterDateTime.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at json_repro.Program.Main(String[] args) in C:\Users\mb\src\tmp\json-repro\Program.cs:line 15
```

Tried debugging, and the issue is here:
https://github.com/dotnet/corefx/blob/da3ba7ebe34771dde769b65dfb7f78fa55a5abb6/src/System.Text.Json/src/System/Text/Json/JsonHelpers.Date.cs#L450-L466

`dateTime` returned from `TryCreateDateTime()` previously is `var dateTime = new DateTime(0, DateTimeKind.Local)`, which means that it will be out of range for a `DateTimeOffset` if UTC offset is larger than 0.

**Comment by mholo65** [comment]
Biggest issue for me is that I'm unable to build and test `System.Text.Json` without adjusting my timezone. 😢

**Comment by mholo65** [comment]
Related to (or possible duplicate of) #38717

**Comment by mholo65** [comment]
Probably same issue with `DateTime.MaxValue` then in time zone with UTC offset smaller than 0 (haven’t tested). `DateTime.MinValue` is however more problematic since it’s the default value of `DateTime`.

**Comment by steveharter** [comment]
@layomia can you take a look please? This may have been fixed.

**Comment by steveharter** [comment]
cc @JeremyKuhne if you still looking at DateTime support.

**Comment by JeremyKuhne** [comment]
@layomia I'll look at this since I'm in this code at the moment.

**Comment by JeremyKuhne** [comment]
Should be ok with #39187.

**Comment by mholo65** [comment]
@JeremyKuhne I tried running tests from your PR branch (#39187), but I am still seeing the same issues.

**Comment by JeremyKuhne** [comment]
> I am still seeing the same issues.

Interesting. I wonder what the difference is? I set myself to UTC + 1 and didn't have a problem.

**Comment by mholo65** [comment]
Weird, well, here's my settings:
![image](https://user-images.githubusercontent.com/7863439/60842995-1a71fb80-a1de-11e9-9202-0002d98923d7.png)

![image](https://user-images.githubusercontent.com/7863439/60842884-e696d600-a1dd-11e9-8dfc-e73ae83ad2cf.png)

Let me know if you'd like me to debug anything.

**Comment by JeremyKuhne** [comment]
@layomia can you try to repro this as well once #39187 goes in?

**Comment by ericstj** [comment]
I can help here.  I repro'ed the original issue.  Building your change and testing now.

**Comment by ericstj** [comment]
Repro'ed with the change, here's the innermost exception:
```
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at System.DateTimeOffset..ctor(DateTime dateTime)
   at System.Text.Json.JsonHelpers.TryCreateDateTimeOffsetInterpretingDataAsLocalTime(DateTimeParseData& parseData, DateTimeOffset& value) in D:\\dotnet\\corefx2\\src\\System.Text.Json\\src\\System\\Text\\Json\\JsonHelpers.Date.cs:line 491
```

**Comment by JeremyKuhne** [comment]
Well that makes total sense. We're trying to smuggle DateTimes in DateTimeOffset. That isn't always possible. I guess we'll have to refactor a bit to pass each type back directly.

cc: @tarekgh

**Comment by tarekgh** [comment]
I am seeing the code is already catching this ArgumentOutOfRangeException. are we failing the operation after that?

https://github.com/dotnet/corefx/blob/b86783ef9525f22b0576278939264897464f9bbd/src/Common/src/CoreLib/System/Buffers/Text/Utf8Parser/Utf8Parser.Date.Helpers.cs#L90

**Comment by ericstj** [comment]
Yeah, it's a "Try" method, so when this fails and returns false the outer call ends up throwing.

This is happening because we're trying to parse as DateTime (which can accept this value) but then we're flowing it through a DateTimeOffset here only to convert back to DateTime.
https://github.com/dotnet/corefx/blob/1247fa7a193e52bc89bc49c4ba6e44739df2dcee/src/System.Text.Json/src/System/Text/Json/JsonHelpers.Date.cs#L18-L41

The fix, as Jeremy mentioned, would be to avoid this smuggling, and instead either go straight to DateTime or DateTimeOffset, depending on what the target type is.

**Comment by tarekgh** [comment]
> The fix, as Jeremy mentioned, would be to avoid this smuggling, and instead either go straight to DateTime or DateTimeOffset, depending on what the target type is.

That make sense.

**Comment by layomia** [comment]
I'm taking a look at this now.

**Comment by markvincze** [comment]
Hey folks,

I checked this issue and #38717, but it's unclear to me if this is fixed already or not.

If I run this code:

```
    public class MyType
    {
        public DateTime MyDateTime { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var json = "{\"MyDateTime\": \"0001-01-01T00:00:00\"}";
            var c = System.Text.Json.JsonSerializer.Deserialize<MyType>(json);

            Console.WriteLine(c.MyDateTime);
        }
    }
```

I'm still getting the `The JSON value could not be converted to System.DateTime` exception.

I'm using version `4.6.0-preview7.19362.9` of `System.Test.Json`, which was released 9 days ago, so #39547 should've been included in it.

Is this a bug which is still not fixed, or am I trying to do something invalid?

**Comment by karelz** [comment]
It was fixed in master (3.0 at that moment) in PR #39541.

@markvincze if you see a problem on latest master or release/3.0 builds, please file a new bug.

**Comment by markvincze** [comment]
Hi @karelz,

Thanks for the info!  
Do you happen to know if there is an easy way for me to check if a specific Nuget release (for example 4.6.0-preview7.19362.9) already contains a certain PR or not? (For example can I check the commit based on which that package was released?

**Comment by mholo65** [comment]
@markvincze the releases are tagged. By looking at the src in preview7 tag I can see that this fix isn’t available in preview7. See https://github.com/dotnet/corefx/commits/v3.0.0-preview7.19362.9/src/System.Text.Json/src

**Comment by markvincze** [comment]
@mholo65 clear, thanks! I'll look out for the next preview and will test it there.

**Comment by mholo65** [comment]
@markvincze if you don’t want to wait for another preview, you can try out the nightly builds as explained here https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

**Comment by markvincze** [comment]
@mholo65 @karelz,
Thanks for help, I verified that the issue is fixed in `4.6.0-preview8.19405.3` 👍
