### ISSUE TITLE
Change System.Net.WebSockets contract for WebSocketReceiveResult

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#4530]
Follow up from "Resuable WebSocketReceiveResult" #4520

At the moment is `WebSocketReceiveResult` is a read only POCO type that as a class must be garbage collected on every single socket message; probably gen0; but still bad for high speed websockets.

I can see two approaches to address this:
1. Change the setters to protected, which opens up a possibility for types derived from `System.Net.WebSockets.WebSocket` to reuse the result object using a derived `WebSocketReceiveResult` type.
2. Change type from `class` to `struct`.

Either approach halves the number of allocations, second is safer but allocates more memory. (Though ValueTask returns could change this)

**Comment by benaadams** [comment]
cc: @davidsh

**Comment by davidfowl** [comment]
I always wondered why it wasn't a struct. Does anyone derive from this type?

**Comment by benaadams** [comment]
While breaking contracts might be useful if it was a `struct` and `ReceiveAsync` returned a [`ValueTask<WebSocketReceiveResult>`](https://github.com/dotnet/corefxlab/blob/master/src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/ValueTask.cs) instead...

**Comment by jasonwilliams200OK** [comment]
(perhaps a rookie question)
How would changing `class` to `struct` makes data reusable?

**Comment by davidsh** [comment]
cc: @CIPop @pgavlin @SidharthNabar @bartonjs @terrajobst

**Comment by benaadams** [comment]
@jasonwilliams200OK it doesn't; it means the GC doesn't allocate an object handle for it which it then needs to check and clean up.

**Comment by CIPop** [comment]
@benaadams Thanks for your input! 
Could you share any perf numbers observed in your real-world scenario when you make this change?

The reasons we can't change the contract is portability between Desktop and CoreCLR. We would consider adding another overload if the perf increase in a real-world scenario justifies it. 

At the same time, please note that we are not yet done with the WebSockets implementation and porting all tests. To avoid destabilizing the implementation, this work will be postponed until we've implemented and tested the existing contract.

> I always wondered why it wasn't a struct. Does anyone derive from this type?

@davidfowl Nothing derives or should be deriving from this type. I don't know/understand the original design decision either. 

> How would changing  class  to  struct  makes data reusable?

@jasonwilliams200OK See https://msdn.microsoft.com/en-us/library/ms173109.aspx for clarification. The short answer is that `struct` is a value-type and will not be managed by GC.

**Comment by jasonwilliams200OK** [comment]
@benaadams, @CIPop thanks for the answers and the link. The answers at http://stackoverflow.com/q/2146434 by @jskeet and @ericlippert further clarified on value-type datastructures' instances are GC-agnostic and instance they are virtually popped out by reverting the CPU stack pointer back when IP goes out of scope (on function return for example).

**Comment by benaadams** [comment]
@jasonwilliams200OK unless they are instance members of a class; but the GC still doesn't pay attention to them - same behaviour as adding an `int` to a class though probably larger.

**Comment by benaadams** [comment]
@CIPop this is a perfview of our current allocators and `WebSocketReceiveResult` is about 17th on the list

![types-allocated](https://aoa.blob.core.windows.net/aspnet/websocketreceive.png)

**Comment by CIPop** [comment]
/cc: @himadrisarkar 

Thanks @benaadams!

**Comment by benaadams** [comment]
After some optimizations and upgrading to aspnet Websocket 0.2.0 which shares corefx's impl

`WebSocketReceiveResult` and `Task<WebSocketReceiveResult>` are items 3 and 5 on our top allocated items:

![web-socket-receive](https://aoa.blob.core.windows.net/aspnet/websocket-result.png)

**Comment by stephentoub** [comment]
@benaadams, I realize this is an aside from the main purpose of your post, but I assume that these moving up on the list speaks well to the rest of the implementation, in that other things higher on the list have been removed?

**Comment by benaadams** [comment]
@stephentoub yes it does, am using the 1.1.0 dotnet-core myget feed :+1: 

There's `ReceiveAsyncPrivate` which is new; but that may just be actual asyncness

**Comment by stephentoub** [comment]
Are those SemaphoreSlim.TaskNodes coming from the websockets implementation? That would imply a lot of concurrent receives or sends (or a bug).

**Comment by benaadams** [comment]
No, is the signalling mechanism for data/no data, looking to do a custom awaiter as its single producer, single consumer.

**Comment by benaadams** [comment]
@stephentoub there are other allocations in websockets (`byte[]` etc); but doesn't seem to anything too major by comparison.

**Comment by davidfowl** [comment]
@CIPop after all of the low hanging fruit, a CopyToAsync implementation would be great 😄

**Comment by davidfowl** [comment]
FWIW, the ASP.NET team are looking at defining an alternate contract for websockets that doesn't require users to allocate a buffer or task per read. Still very early though.

/cc @anurse

**Comment by CIPop** [comment]
> The reasons we can't change the contract is portability between Desktop and CoreCLR. We would consider adding another overload if the perf increase in a real-world scenario justifies it.

@benaadams I think we can't change the existing APIs. `WebSocketReceiveResult` is part of [netstandard](https://github.com/dotnet/standard/blob/master/netstandard/ref/System.cs#L7895).

I still think this would be a good idea but it'll require adding new APIs in System.Net.WebSockets that return the structs instead. While perf will be improved, the API surface will not.

@terrajobst @weshaggard @karelz would having both APIs be allowed? (We would need to add `StructWebSocketReceiveResult` as a new struct type to the public API as well.)

```C#
      public abstract System.Threading.Tasks.Task<System.Net.WebSockets.WebSocketReceiveResult> ReceiveAsync(System.ArraySegment<byte> buffer, System.Threading.CancellationToken cancellationToken);
// and something on the lines of:
      public abstract System.Threading.Tasks.Task<StructWebSocketReceiveResult> ReceiveAsync(System.ArraySegment<byte> buffer, System.Threading.CancellationToken cancellationToken);       
```

**Comment by karelz** [comment]
You cannot overload method on return type, but in principle if there is non-trivial perf benefit, I'd be ok adding new API.
@davidfowl is it based on Channels/Pipelines (or whatever the current name is)? In that case we might want to wait for that API, instead of trying to patch up performance of current stack.

@geoffkizer @benaadams any opinions?

**Comment by benaadams** [comment]
It would have to be virtual and wrap the current method in the base as there are multiple implementations of it already.

I think its worth addressing, as it is the standard WebSocket base that everything implements. Even Pipelines would likely have to provide a derivation of it in some way (even if just a wrapper transform).

If adding a new method; I wouldn't just stop at the struct return, but go all the way... Since is return max size of message; rather than max size of buffer you can have many messages in the buffer so the call has the opportunity to sync complete more frequently. 

So either `ValueTask` with a struct return
```csharp
public virtual ValueTask<WebSocketMessageReceiveResult> 
    ReceiveAsync(
        ArraySegment<byte> buffer, 
        CancellationToken cancellationToken);
```

Alternatively, don't change the Receive function at all; since it is already a class; and since only one Receive can happen at once (else I think it throws); you could add an extra property to the `WebSocket`
```csharp
public bool AllowReceiveResultReuse { get; set; }
```

Then derived classes could optionally reuse the same instance and also the same cached task with that instance and just change the values?

**Comment by benaadams** [comment]
May be resolved by https://github.com/dotnet/corefx/issues/21281

```chsarp
public virtual ValueTask<ValueWebSocketReceiveResult> 
    ReceiveAsync(Buffer<byte> buffer, CancellationToken cancellationToken = default(CancellationToken));
```

**Comment by stephentoub** [comment]
Replaced by https://github.com/dotnet/corefx/issues/22610.  If anyone feels otherwise, please feel free to comment/re-open.
