### ISSUE TITLE
Cannot compile CoreFX on Linux anymore

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/corefx#6128]
There is a MSBuild failure when you build CoreFX on Ubuntu 14.04:

```
./build.sh
Setting up directories for build
Restoring NuGet.exe...
Installing dotnet cli...
Restoring BuildTools version 1.0.25-prerelease-00167...
Initializing BuildTools...
Done initializing tools.
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.EntryPointNotFoundException: Unable to find an entry point named 'Stat' in DLL 'System.Native'.
   at Interop.Sys.Stat(String path, FileStatus& output)
   at System.IO.UnixFileSystem.DirectoryExists(String fullPath)
   at System.IO.Directory.Exists(String path)
   at Microsoft.Build.Shared.FileUtilities.LooksLikeUnixFilePath(String value)
   at Microsoft.Build.CommandLine.MSBuildApp.GatherCommandLineSwitches(ArrayList commandLineArgs, CommandLineSwitches commandLineSwitches)
   at Microsoft.Build.CommandLine.MSBuildApp.GatherAllSwitches(String[] commandLine, CommandLineSwitches& switchesFromAutoResponseFile, CommandLineSwitches& switchesNotFromAutoResponseFile)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'Stat' in DLL 'System.Native'.
   at Interop.Sys.Stat(String path, FileStatus& output)
   at System.IO.UnixFileSystem.DirectoryExists(String fullPath)
   at System.IO.Directory.Exists(String path)
   at Microsoft.Build.Shared.FileUtilities.LooksLikeUnixFilePath(String value)
   at Microsoft.Build.CommandLine.MSBuildApp.GatherCommandLineSwitches(ArrayList commandLineArgs, CommandLineSwitches commandLineSwitches)
   at Microsoft.Build.CommandLine.MSBuildApp.GatherAllSwitches(String[] commandLine, CommandLineSwitches& switchesFromAutoResponseFile, CommandLineSwitches& switchesNotFromAutoResponseFile)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
./build.sh: line 100: 12558 Aborted                 (core dumped) ReferenceAssemblyRoot=$__referenceassemblyroot $__scriptpath/Tools/corerun $__scriptpath/Tools/MSBuild.exe "$__buildproj" /nologo /verbosity:minimal "/fileloggerparameters:Verbosity=normal;LogFile=$__buildlog" "/l:BinClashLogger,$__binclashloggerdll;LogFile=$__binclashlog" /t:Build /p:OSGroup=$__BuildOS /p:COMPUTERNAME=$(hostname) /p:USERNAME=$(id -un) /p:TestNugetRuntimeId=$__TestNugetRuntimeId $__UnprocessedBuildArgs
```

**Comment by sejongoh** [comment]
I also see the same problem on my machine as well as on CI.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_ubuntu_release/8/console

**Comment by stephentoub** [comment]
Somehow the packages being used appear to be out of sync... older managed bits are being used with newer native bits (the function in question was renamed several months ago, in both the native and managed sources, but the managed binary is still looking for the old name).

**Comment by weshaggard** [comment]
@joperezr can you please take a look.

**Comment by joperezr** [comment]
looks like the issue is that during the restore of the runtime in buildtools, two packages are being restored with older versions: "System.IO.FileSystem" and "System.Security.Cryptography.Algorithms". We have a (workaround) fix for this by specifically includding those two in the buildtools runtime project.json. @dagood is currently working on the change and we'll get it merged ASAP

**Comment by joperezr** [comment]
Linux builds are fixed with change #6089

**Comment by joperezr** [comment]
Code has been merged, corefx should build again in linux, so I'm closing this issue now.

**Comment by ianhays** [comment]
I'm seeing a similar issue when trying to build the tests for System.IO.FileSystem on Ubuntu 14.04

```
 System.IO.Tests.FileInfo_CopyTo_str_b.UnixWhitespacePath [FAIL]
        System.EntryPointNotFoundException : Unable to find an entry point named 'SystemNative_CopyFile' in DLL 'System.Native'.
        Stack Trace:
              at Interop.Sys.CopyFile(SafeFileHandle source, SafeFileHandle destination)
              at System.IO.UnixFileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
              at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite)
              at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
              at System.IO.Tests.FileInfo_CopyTo_str_b.Copy(String source, String dest)
              at System.IO.Tests.File_Copy_str_str.UnixWhitespacePath()
```

I'm assuming it has something to with how we're restoring the native components.

I'm running the tests using ```msbuild /t:BuildAndTest /p:Configuration=Linux_Debug from ~/corefx/src/System.IO.FilSystem/tests```

I tried deleting Tools, packages, and Bin as well as running clean.sh but the issue remains.
