### ISSUE TITLE
HttpClient Unstable on CoreCLR

### ISSUE THREAD

**Issue by brentarias** [dotnet/corefx#8440]
I've been using HttpClient in my ASP.NET Core application, running on the (full) `clr` runtime.  It works great.  However, when I  `dnvm use` to switch to `coreclr` runtime, then I've found that HttpClient invocations fail.  At first this seems like this is a Kestrel issue, but please read my post through to learn my workaround.  The workaround suggests this is an issue with HttpClient itself.

To create this problem:

 * Run under `1.0.0-rc1-update2 coreclr`.   I use `x86` for architecture, but I don't think that matters.
 * Execute an HttpClient request **in an async / await construct**.  This part is necessary!
 * Perform back-to-back HttpClient POST requests that serialize payload (I have been using `Microsoft.AspNet.WebApi.Client v5.2.3` extensions, such as `PostAsJsonAsync`).

I launch the test by typing `dnx test`, which launches xUnit.  The first HttpClient request will work correctly.  The next request will mysteriously receive a 404.  

When I insert fiddler to spy on traffic, it interferes by "post-poning" the problem; it allows two or three HttpClient requests to be processed before finally failing with a 404.  Furthermore, Fiddler will only capture half or less of the traffic(!!!!) being received by Kestrel (even though all requests are coming from the same HttpClient object instance!).  

One of the 404 requests that was captured by both Fiddler and Kestrel looked like this:

```
PATCH http://localhost:60996/evt/Subscribers/bcf8edb0-dbae-4e83-bb8d-b5d966b2736b/AddNumbers HTTP/1.1
Content-Type: application/json; charset=utf-8
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
Host: localhost:60996
Content-Length: 15

["303 2968199"]
```

Looks normal.  On the Kestrel side, it looks like this:

```
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1
      PATCH http://localhost:60996/evt/Subscribers/bcf8edb0-dbae-4e83-bb8d-b5d966b2736b/AddNumbers application/json; charset=utf-8
verb: Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute[0]
      Request successfully matched the route with name '' and template 'evt/Subscribers/{id}/AddNumbers'.
verb: Microsoft.AspNet.Mvc.Infrastructure.DefaultActionSelector[0]
      Action 'ApiBasics.Controllers.SubscribersController.AddNumbers' with id 'b482e6ad-649c-4885-9b7d-12a25e3b422a' did not match the constraint 'Microsoft.AspNet.Mvc.ActionConstraints.HttpMethodConstraint'
verb: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[3]
      No actions matched the current request
verb: Microsoft.AspNet.Builder.RouterMiddleware[0]
      Request did not match any routes.
```
It would seem this is a Kestrel problem, but consider the workaround.  If I simply Dispose() the HttpClient after every request, and re-create it fresh for each subsequent request - then I can successfully run this code on coreclr.  Furthermore, if I don't use async/await constructs with HttpClient, then this problem also does not appear.  Evidently, there is some sort of state that HttpClient is retaining between calls. 

Again, this work-around is not necessary and the problem does not occur **if I use dnvm to switch to `1.0.0-rc1-update2 clr`** and then run my test again.

I'm launching my test via xUnit.  I have an xUnit `IClassFixture` which launches Kestrel.  In other words, I am performing in-memory fast integration tests.  The versions I am using for these two tools are:

    "xunit.runner.dnx": "2.1.0-rc1-build204",
    "xunit": "2.2.0-beta1-build3239",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",

## Work-around Test Code

To simplify my ability to test the "restart HttpClient" work-around, I have been using this code:

    public class AsyncClient
    {
        Uri address;
        HttpClient client;
        public AsyncClient(Uri baseAddress)
        {
            address = baseAddress;
            client = new HttpClient();
            client.BaseAddress = baseAddress;
        }

        public async Task<HttpResponseMessage> Request(Func<HttpClient, Task<HttpResponseMessage>> call)
        {
            HttpResponseMessage response = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = address;
                response = await call(client);
            }
            return response;
        }
    }

The above `AsyncClient` is registered as a singleton in my IOC container.  By simply commenting the "using" line in the `Request` method, I can toggle between a singleton `HttpClient` or a "per invocation" `HttpClient`.

## Further Anomaly

Using the `AsyncClient` code shown above, I can ensure the `HttpClient` is fresh for every request - and this allows the `coreclr` execution to be successful.  However, when I change the address of the server so that Fiddler can intercept traffic, then this 404 problem occurs all over again!!!!

So if the `HttpClient` base address normally points here:

    http://localhost:60996

And I change that address (for Fiddler's sake) to this address:

    http://localhost.fiddler:60996

Then the same 404 appears after the third or fourth request!  And this time, my "workaround" can't save me...the `coreclr` execution simply will not work...due to these 404 issues.  No Fiddler for `coreclr` !!!

Incidentally, if I switch back to the full `clr` runtime...my errors might be gone, but Fiddler still only captures half the traffic that Kestrel is successfully receiving.  Queue twilight zone music. :sweat:

**Comment by davidsh** [comment]
@brentarias Thank you for the detailed write-up of the issue you're having.  There have been many changes to the codebase since the beta/pre-release packages were published to NuGet.org. It's very possible that the issue you're having is already fixed in our latest packages. We will be publishing updated pre-release packages (RC2) to NuGet.org sometime within the next week or so.

Is it possible for you to also see if this issue repros in the latest packages available on the MYGET feed?
https://dotnet.myget.org/gallery/dotnet-core

**Comment by brentarias** [comment]
Which of the following should I use?

 * https://www.myget.org/F/aspnetcirelease/api/v3/index.json
 * https://www.myget.org/F/aspnetvnext/api/v3/index.json

Both offer RC2 versions of System.Net.Http.  I think I need to select an RC2 version that is still compatible with the `dnx` run-time (e.g. December-ish release).  I say this because, if I understand correctly, "latest" RC2 (1.0.0-rc2-20221) cannot be used with the `dnx` toolset.  Instead, I think it requires the `dotnet CLI` tooling and I think:

 * There is not yet any integrated IDE debugging for `dotnet CLI`.  Neither VS 2015 nor Visual Studio Code support it.
 * There isn't any documentation for how to transition a package.json for `dotnet CLI` compatibility.
 * The package.json format for `dotnet CLI` is undergoing change even now, so targeting it is difficult.
 
Correct?

Also, what about Microsoft.AspNet.WebApi.Client v5.2.3?  I've not found a myget feed that has a newer version to try?  Do you know where that might be?

**Comment by svick** [comment]
@brentarias ASP.NET core has [a page explaining their MyGet feeds](https://github.com/aspnet/Home/wiki/NuGet-feeds).

**Comment by brentarias** [comment]
I have now re-tested HttpClient with the following:

 * runtime: rc1-update2 coreclr 
 * "System.Net.Http": "4.0.1-rc2-23826"

The problem I documented still occurs as of those versions.  I cannot test anything later than that without having to re-instrument my entire solution for the rc2 runtime.

**Comment by davidsh** [comment]
@brentarias Can you attach Fiddler traces and also NetMon traces so we can diagnose?

Getting a 404 back from the Kestrel server is not an HttpClient bug, per se.  But perhaps HttpClient is sending something unexpected to the Kestrel server.  So, we need to understand the flow better.

**Comment by davidsh** [comment]
@brentarias RC2 has shipped today. Can you please refresh your project repro using RC2 tools and packages (i.e. dotnet cli tool, etc.) Thx.

**Comment by davidsh** [comment]
@brentarias Can you retry this on RC2 or latest RTM candidate packages?  Please re-open this if you are able to repro again.  Thx.
