### ISSUE TITLE
Console.ReadKey returns escape sequence instead of expected key on Ubuntu 14.04

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#8912]
Code snippit:
```
while (true)
{
    var key = Console.ReadKey(true).Key;
    Console.WriteLine(key);
}
```
Pressing the right and left arrow outputs:
```
Escape
C
Escape
D
```
Expected output:
```
RightArrow
LeftArrow
```

**Comment by stephentoub** [comment]
What terminal are you using?  What's the value of the TERM environment variable? etc.

Your repro works fine for me.  Most likely the issue is that you have a mismatch between the terminal being used, what's set as the TERM environment variable, and thus what terminfo file is being used, with sequences defined that don't match the sequences being sent.  Or something like that.

**Comment by tmds** [comment]
I've started the 'Terminal' app in my desktop environment which has:
```
TERM=xterm
COLORTERM=gnome-terminal
```

**Comment by stephentoub** [comment]
What do you see if you type ```sed -n l```, then right arrow and left arrow, and then enter?

And what is the output from ```infocmp xterm```?

**Comment by stephentoub** [comment]
Also, did you do any special configuration of your terminal, above what comes in a default Ubuntu 14.04 install?  Did you modify your startup scripts at all? Etc.

**Comment by tmds** [comment]
I just created a new user on my machine and the behavior is exactly the same in that account.

sed -n l output
```
^[[C^[[D
\033[C\033[D$
```

infocmp xterm output
```
#	Reconstructed via infocmp from file: /lib/terminfo/x/xterm
xterm|xterm-debian|X11 terminal emulator,
	am, bce, km, mc5i, mir, msgr, npc, xenl,
	colors#8, cols#80, it#8, lines#24, pairs#64,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
	dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K, el1=\E[1K,
	flash=\E[?5h$<100/>\E[?5l, home=\E[H, hpa=\E[%i%p1%dG,
	ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
	ind=^J, indn=\E[%p1%dS, invis=\E[8m,
	is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~, kEND=\E[1;2F,
	kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D, kNXT=\E[6;2~,
	kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=\177, kcbt=\E[Z,
	kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
	kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
	kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
	memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
	rin=\E[%p1%dT, rmacs=\E(B, rmam=\E[?7l, rmcup=\E[?1049l,
	rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
	rs1=\Ec, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
	setab=\E[4%p1%dm, setaf=\E[3%p1%dm,
	setb=\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
	setf=\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, smacs=\E(0, smam=\E[?7h, smcup=\E[?1049h,
	smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m, smul=\E[4m,
	tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?1;2c, u9=\E[c,
	vpa=\E[%i%p1%dd,

``````

**Comment by tmds** [comment]
I've just tested the behavior on a Debian 8 machine, it doesn't work either.

**Comment by stephentoub** [comment]
What build are you using?  How are you building / running the repro?  I'm unable to repro the behavior you're seeing.  @ianhays, are you?  @ellismg?

**Comment by tmds** [comment]
project.json
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },

  "tooling": {
    "defaultNamespace": "ConsoleTest"
  }
}
```
Program.cs
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleTest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            while (true)
            {
                var key = Console.ReadKey(true).Key;
                Console.WriteLine(key);
            }
        }
    }
}
```
NuGet Config files used:
    /home/tmds/.nuget/NuGet/NuGet.Config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```
dotnet --version
```
1.0.0-preview1-002702
```

**Comment by ellismg** [comment]
Also, what is $LANG set to?

**Comment by ianhays** [comment]
This reproes for me.

**Comment by ianhays** [comment]
$ echo $LANG
en_US.UTF-8

**Comment by ianhays** [comment]
This appears to be an issue in the CLI runner in version 1.0.0-preview1-002702.

Running the dll produced by the CLI on corerun functions as expected:
```
~/testcli/firstapp/bin/Debug/netcoreapp1.0$ ~/git/corefx/Tools/corerun firstapp.dll
RightArrow
LeftArrow
Enter
```

**Comment by stephentoub** [comment]
Thanks, @ianhays. Yeah, this is why I asked how it was being built / run.  I expect it has to do with how "dotnet run" is scheduling the process in that particular build.  Note that I'm not able to repro using either corerun or a more recent "preview2" CLI build.

**Comment by tmds** [comment]
How does the cli affect the key readout? Is this a known issue which was fixed in the cli?

**Comment by stephentoub** [comment]
> How does the cli affect the key readout?

Understanding how to interpret keys is impacted by the environment, by environment variables, by redirection, etc.  "dotnet run" runs another process that then invokes the app that got compiled.  There are a variety of ways that shelling out to another process could impact the environment as seen by the running app.

If you try a newer CLI and find this issue fixed with "dotnet run", I expect it was addressed as a side-effect of a change like https://github.com/dotnet/cli/pull/3013, or something else that similarly impacted the set up of the process.

**Comment by tmds** [comment]
Strange enough if I set TERM to linux it works.
I'll close the issue and re-open in case it isn't fixed when I switch to preview2.
Thanks for the quick follow-up.
