### ISSUE TITLE
X509Certificate2.GetECDsaPrivateKey fails

### ISSUE THREAD

**Issue by vcsjones** [dotnet/corefx#9070]
I have a certificate in the certificate store that `GetECDsaPrivateKey` fails on in Windows Server 2012 R2. It fails with the exception:

>Keys used with the ECDsaCng algorithm must have an algorithm group of ECDsa.
Parameter name: key

First, some details on the certificate. It is a self signed (for now) certificate with a 256-bit ECC key, the public key parameters are ECDSA_P256. The keyUsage extension is Critical:digitalSignature (80) and the EKU is codeSigning. The certificate was added to the certificate store using the import wizard when opening a PKCS12 file.

When I platform invoke CNG myself with `CryptAcquireCertificatePrivateKey` and pass the key handle to `CngKey.Open` the same way the CertificatePal does it [here](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/CertificatePal.PrivateKey.cs#L66), I see that the CngKey is believed to be ECDH and has a key usage of "AllUsage".

Regardless, I need an ECDsa instance for this certificate. What is the trick to getting CNG / GetECDsaPrivateKey is a ECDSA key, not an ECDH?

There really isn't a difference between an ECDSA key or an ECDH key, as long as you don't use the same key for both purposes, so I would think this should work.

/cc @bartonjs

**Comment by bartonjs** [comment]
Is this on .NET Core, or .NET Framework?  And, if Framework, which version?

**Comment by vcsjones** [comment]
This was desktop .NET Framework net461. I'll try with rc2 in a moment.

**Comment by bartonjs** [comment]
@vcsjones Oh, good, I like when my psychic debugging works :smile:.

In Core this was #3771, which got fixed in net462 preview.

https://github.com/Microsoft/dotnet/blob/master/releases/net462/dotnet462-changes.md

> Improved interoperability with PFX files created with OpenSSL in GetECDsaPrivateKey. [171017]

So I'd expect that you'll see success in core-rc2, and if you install net462-preview it should also work there.

**Comment by vcsjones** [comment]
Wow. Good call.

Here's what is going on, I think and why it works on Windows and not openssl.

When you create the key on Windows, the CNG key gets the "Key Usage" attribute set on the key in the KSP. Crucially, when you export the certificate with the CNG key to PKCS#12, the key usage gets set as an attribute in the PKCS#12 structure called Key Attributes.

When doing this with openssl, there is no concept of key usage on the key itself. When it creates the PKCS#12 file, "Key attributes" gets set to nothing.

You can fix this with openssl PKCS#12 files by using the `-keysig` arg to openssl.

So, for .NET Framework 4.6.1 people, use `-keysig` when using OpenSSL to create PKCS#12 that windows correctly marks the key usage on.

**Comment by bartonjs** [comment]
@vcsjones Cool; so it sounds like everything here's happy, and that you found a way to do a workaround for net461.  Is there anything else that you think is missing. or can we close the issue?

**Comment by bartonjs** [comment]
(I'm glad I didn't know the workaround at the time, or I might not have made it "just work" :))

**Comment by vcsjones** [comment]
No, I think this is closable. Thanks for putting me in the right direction.

Making it "just work" is still a valid case; if a key's usage is `All Usages`, CNG will still present it as ECDH, even though it's perfectly valid for using as a ECDSA key.

It's a bit unfortunate the CNG forces a key to have an algorithm when a key can be used for more than one algorithm.

**Comment by bartonjs** [comment]
Yeah, I agree on all counts.  Just that if I'd known there was a workaround I might've decided something else was more important to fix that day :)

**Comment by MikeRosoft** [comment]
It looks like I have just stepped into an opposite problem. I have a certificate which is marked for usage = 'Key/Data encipherment" (encryption), and when I try to retrieve its private key, I get the same exception. Note: I don't know in advance if the certificate is an RSA certificate or an ECC certificate. What should I do?

The exception occurred on Windows 10 in a .NET Framework 4.7 application.
